/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import static frames.Registro.Imagen;
import static frames.Registro.apellido;
import static frames.Registro.contrasenia;
import static frames.Registro.correo;
import static frames.Registro.fecha;
import static frames.Registro.id_pais;
import static frames.Registro.id_sexo;
import static frames.Registro.nombre;
import static frames.Registro.pais;
import static frames.Registro.telefono;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class Ajustes extends javax.swing.JDialog {

    /**
     * Creates new form Ajustes
     */
    
    
    public String sexo, ruta;
    public int id_sexo;
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    boolean pic=false;
    
    public Ajustes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        CampoNombre.setText(Registro.nombre);
        CampoApellido.setText(Registro.apellido);
        CampoCorreo.setText(Registro.correo);
        CampoContrasenia.setText(Registro.contrasenia);
        CampoTelefono.setText(Registro.telefono);
        CampoFecha.setText(Registro.fecha);
        CampoPais.setSelectedIndex(Registro.id_pais);
        if (Registro.id_sexo == 1){
            
            hombre.setSelected(true);
        } else if (Registro.id_sexo == 2){
            
            mujer.setSelected(true);
            
        } else {
            
            otro.setSelected(true);
        }
        
        if (Registro.ruta == null) {
            
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/square (1).png"));
            Imagen.setIcon(icon);
            
        } else {

            ImageIcon icon = new ImageIcon(Registro.ruta);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
            Imagen.setIcon(icono);
        
        }
        
        error1.setVisible(false);
        error2.setVisible(false);
        error3.setVisible(false);
        
    }

        public byte[] AbrirArchivo(File archivo) {
        
        byte[] imagen = new byte[1024*100];
        try {
            entrada = new FileInputStream(archivo);
            entrada.read(imagen);
        } catch (Exception e) {
            
        }
        return imagen;
    }
    
    public String GuardarArchivo (File archivo, byte[] imagen) {
        
        String msj = null;
        try {
            salida = new FileOutputStream(archivo);
            salida.write(imagen);
            msj = "Archivo Guardado";
        } catch (Exception e) {
        }
        return msj;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSexo = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        CampoNombre = new rojeru_san.RSMTextFull();
        CampoCorreo = new rojeru_san.RSMTextFull();
        CampoApellido = new rojeru_san.RSMTextFull();
        CampoContrasenia = new rojeru_san.RSMPassView();
        CampoTelefono = new rojeru_san.RSMTextFull();
        CampoPais = new javax.swing.JComboBox();
        otro = new javax.swing.JRadioButton();
        hombre = new javax.swing.JRadioButton();
        mujer = new javax.swing.JRadioButton();
        BotonContinuar = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        error3 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        CampoFecha = new rojeru_san.RSMTextFull();
        BotonCambiar = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        BotonCerrar = new rojeru_san.RSButton();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        fondo1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1757, 917));
        setSize(new java.awt.Dimension(1757, 917));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoNombre.setForeground(new java.awt.Color(0, 0, 0));
        CampoNombre.setBordeColorFocus(new java.awt.Color(181, 18, 27));
        CampoNombre.setBotonColor(new java.awt.Color(181, 18, 27));
        CampoNombre.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        CampoNombre.setPlaceholder("nombre ");
        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });
        CampoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoNombreKeyTyped(evt);
            }
        });
        panel.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 390, 80));

        CampoCorreo.setForeground(new java.awt.Color(0, 0, 0));
        CampoCorreo.setBordeColorFocus(new java.awt.Color(181, 18, 27));
        CampoCorreo.setBotonColor(new java.awt.Color(181, 18, 27));
        CampoCorreo.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        CampoCorreo.setPlaceholder("correo electrónico");
        CampoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorreoActionPerformed(evt);
            }
        });
        CampoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCorreoKeyTyped(evt);
            }
        });
        panel.add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 760, 80));

        CampoApellido.setForeground(new java.awt.Color(0, 0, 0));
        CampoApellido.setBordeColorFocus(new java.awt.Color(181, 18, 27));
        CampoApellido.setBotonColor(new java.awt.Color(181, 18, 27));
        CampoApellido.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        CampoApellido.setPlaceholder("apellido");
        CampoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoApellidoActionPerformed(evt);
            }
        });
        CampoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoApellidoKeyTyped(evt);
            }
        });
        panel.add(CampoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 390, 80));

        CampoContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        CampoContrasenia.setBordeColorFocus(new java.awt.Color(181, 18, 27));
        CampoContrasenia.setBotonColor(new java.awt.Color(181, 18, 27));
        CampoContrasenia.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        CampoContrasenia.setPlaceholder("contraseña");
        CampoContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoContraseniaKeyTyped(evt);
            }
        });
        panel.add(CampoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 760, 90));

        CampoTelefono.setForeground(new java.awt.Color(0, 0, 0));
        CampoTelefono.setBordeColorFocus(new java.awt.Color(181, 18, 27));
        CampoTelefono.setBotonColor(new java.awt.Color(181, 18, 27));
        CampoTelefono.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        CampoTelefono.setPlaceholder("teléfono");
        CampoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefonoActionPerformed(evt);
            }
        });
        CampoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoTelefonoKeyTyped(evt);
            }
        });
        panel.add(CampoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 760, 90));

        CampoPais.setEditable(true);
        CampoPais.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        CampoPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione país de nacimiento ", "Afganistán ", "Albania  ", "Alemania ", "Andorra ", "Angola Antigua y Barbuda ", "Arabia Saudita ", "Argelia ", "Argentina ", "Armenia ", "Australia ", "Austria ", "Azerbaiyán ", "Bahamas ", "Bangladés ", "Barbados ", "Baréin ", "Bélgica ", "Belice ", "Benín ", "Bielorrusia ", "Birmania ", "Bolivia ", "Bosnia y Herzegovina ", "Botsuana ", "Brasil ", "Brunéi ", "Bulgaria ", "Burkina Faso ", "Burundi ", "Bután ", "Cabo Verde", "Camboya ", "Camerún ", "Canadá ", "Catar ", "Chad ", "Chile ", "China ", "Chipre ", "Ciudad del Vaticano ", "Colombia ", "Comoras ", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica ", "Croacia ", "Cuba ", "Dinamarca ", "Dominica ", "Ecuador ", "Egipto ", "El Salvador ", "Emiratos Árabes Unidos ", "Eritrea ", "Eslovaquia ", "Eslovenia", "España ", "Estados Unidos ", "Estonia ", "Etiopía ", "Filipinas ", "Finlandia ", "Fiyi ", "Francia ", "Gabón ", "Gambia ", "Georgia ", "Ghana ", "Granada ", "Grecia ", "Guatemala ", "Guyana ", "Guinea ", "Guinea ecuatorial ", "Guinea-Bisáu ", "Haití ", "Honduras ", "Hungría ", "India ", "Indonesia ", "Irak ", "Irán ", "Irlanda ", "Islandia ", "Islas Marshall ", "Islas Salomón ", "Israel ", "Italia ", "Jamaica ", "Japón ", "Jordania ", "Kazajistán ", "Kenia ", "Kirguistán ", "Kiribati ", "Kuwait ", "Laos ", "Lesoto ", "Letonia ", "Líbano ", "Liberia ", "Libia ", "Liechtenstein ", "Lituania ", "Luxemburgo ", "Macedonia del Norte ", "Madagascar ", "Malasia ", "Malaui ", "Maldivas ", "Malí ", "Malta ", "Marruecos ", "Mauricio ", "Mauritania ", "México ", "Micronesia", "Moldavia ", "Mónaco ", "Mongolia ", "Montenegro ", "Mozambique ", "Namibia ", "Nauru ", "Nepal ", "Nicaragua ", "Níger ", "Nigeria ", "Noruega ", "Nueva Zelanda ", "Omán ", "Países Bajos ", "Pakistán ", "Palaos ", "Panamá ", "Papúa ", "Nueva Guinea ", "Paraguay", "Perú ", "Polonia ", "Portugal ", "Reino Unido ", "República Centroafricana ", "República Checa ", "República del Congo ", "República Democrática del Congo ", "República Dominicana ", "República Sudafricana ", "Ruanda ", "Rumanía ", "Rusia ", "Samoa ", "San Cristóbal y Nieves ", "San Marino ", "San Vicente y las Granadinas ", "Santa Lucía ", "Santo Tomé y Príncipe ", "Senegal ", "Serbia ", "Seychelles ", "Sierra Leona ", "Singapur ", "Siria ", "Somalia ", "Sri Lanka ", "Suazilandia ", "Sudán ", "Sudán del Sur ", "Suecia ", "Suiza ", "Surinam ", "Tailandia ", "Tanzania ", "Tayikistán ", "Timor Oriental ", "Togo ", "Tonga ", "Trinidad y Tobago ", "Túnez ", "Turkmenistán ", "Turquía ", "Tuvalu ", "Ucrania ", "Uganda ", "Uruguay ", "Uzbekistán ", "Vanuatu ", "Venezuela ", "Vietnam ", "Yemen ", "Yibuti", "Zambia ", "Zimbabue" }));
        CampoPais.setFocusable(false);
        CampoPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoPaisKeyTyped(evt);
            }
        });
        panel.add(CampoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 760, 90));

        otro.setBackground(new java.awt.Color(255, 255, 255));
        GrupoSexo.add(otro);
        otro.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        otro.setText("Otro");
        otro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otroMouseClicked(evt);
            }
        });
        otro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otroKeyTyped(evt);
            }
        });
        panel.add(otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, 150, 80));

        hombre.setBackground(new java.awt.Color(255, 255, 255));
        GrupoSexo.add(hombre);
        hombre.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        hombre.setText("Hombre");
        hombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hombreMouseClicked(evt);
            }
        });
        hombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hombreKeyTyped(evt);
            }
        });
        panel.add(hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 220, 80));

        mujer.setBackground(new java.awt.Color(255, 255, 255));
        GrupoSexo.add(mujer);
        mujer.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        mujer.setText("Mujer");
        mujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mujerMouseClicked(evt);
            }
        });
        mujer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mujerKeyTyped(evt);
            }
        });
        panel.add(mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 190, 80));

        BotonContinuar.setBackground(new java.awt.Color(255, 255, 255));
        BotonContinuar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BotonContinuar.setText(">");
        BotonContinuar.setBorderPainted(false);
        BotonContinuar.setColorHover(new java.awt.Color(79, 186, 111));
        BotonContinuar.setColorText(new java.awt.Color(0, 0, 0));
        BotonContinuar.setFocusPainted(false);
        BotonContinuar.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        BotonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonContinuarMouseClicked(evt);
            }
        });
        panel.add(BotonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 680, 100, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel (2).png"))); // NOI18N
        jPanel1.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 70));

        error2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel (2).png"))); // NOI18N
        jPanel1.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        error1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel (2).png"))); // NOI18N
        jPanel1.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        CampoFecha.setForeground(new java.awt.Color(0, 0, 0));
        CampoFecha.setBordeColorFocus(new java.awt.Color(181, 18, 27));
        CampoFecha.setBotonColor(new java.awt.Color(181, 18, 27));
        CampoFecha.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        CampoFecha.setPlaceholder("fecha");
        jPanel1.add(CampoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 760, 100));

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 720));

        BotonCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-button-inside-black-circle (4).png"))); // NOI18N
        BotonCambiar.setEnabled(false);
        BotonCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCambiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCambiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCambiarMouseExited(evt);
            }
        });
        BotonCambiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BotonCambiarKeyTyped(evt);
            }
        });
        panel.add(BotonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 470, 150, 150));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square (1).png"))); // NOI18N
        Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenMouseClicked(evt);
            }
        });
        panel.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 520, 520));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setBorder(null);
        BotonCerrar.setText("X");
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setColorHover(new java.awt.Color(204, 4, 17));
        BotonCerrar.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar.setFocusable(false);
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        panel.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 90, 80));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 1590, 770));
        getContentPane().add(rSPanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1740, 900));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, -80, -1, 910));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 750, 1480, 530));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1480, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void CampoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoActionPerformed

    private void CampoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidoActionPerformed

    private void hombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hombreMouseClicked
        
    }//GEN-LAST:event_hombreMouseClicked

    private void mujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mujerMouseClicked
        
    }//GEN-LAST:event_mujerMouseClicked

    private void otroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otroMouseClicked
        
    }//GEN-LAST:event_otroMouseClicked

    private void BotonContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonContinuarMouseClicked

        iniciar();

    }//GEN-LAST:event_BotonContinuarMouseClicked

    private void BotonCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCambiarMouseClicked
          if (seleccionar.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
                
                archivo = seleccionar.getSelectedFile();
                Registro.ruta = seleccionar.getSelectedFile().getAbsolutePath();
                if (archivo.canRead()) {
                    
                    if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png") || archivo.getName().endsWith("gif"));
                    byte[] imagen=AbrirArchivo(archivo);
                    ImageIcon icon = new ImageIcon(imagen);
                    Icon icono = new ImageIcon(icon.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
                    Imagen.setIcon(icono);
                    pic = true;
                    
                    
                    if (seleccionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
                        
                        archivo = seleccionar.getSelectedFile();
                        
                        if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png") || archivo.getName().endsWith("gif")) {
                            
                            String respuesta = GuardarArchivo(archivo, imagen);
                            
                            if (respuesta != null) {
                                
                                JOptionPane.showMessageDialog(null, respuesta);
                                
                            } else {
                                
                                JOptionPane.showMessageDialog(null, "Archivo no Guardado");
                                
                            }
                            
                        }else {
                            
                            JOptionPane.showMessageDialog(null, "Archivo Guardado");
                            
                        }
                        
                    }
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Error! Archivo no compatible", "", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }     // TODO add your handling code here:
    }//GEN-LAST:event_BotonCambiarMouseClicked

    private void BotonCambiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCambiarMouseEntered
        BotonCambiar.setEnabled(true);
    }//GEN-LAST:event_BotonCambiarMouseEntered

    private void BotonCambiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCambiarMouseExited
        BotonCambiar.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCambiarMouseExited

    private void ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseClicked

    }//GEN-LAST:event_ImagenMouseClicked

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        this.dispose();

    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void CampoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNombreKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreKeyTyped

    private void CampoApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidoKeyPressed

    private void CampoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoApellidoKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidoKeyTyped

    private void CampoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCorreoKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoKeyTyped

    private void CampoContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoContraseniaKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseniaKeyTyped

    private void CampoPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPaisKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_CampoPaisKeyTyped

    private void hombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hombreKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_hombreKeyTyped

    private void mujerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mujerKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_mujerKeyTyped

    private void otroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otroKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_otroKeyTyped

    private void BotonCambiarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonCambiarKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_BotonCambiarKeyTyped

    private void CampoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefonoActionPerformed

    private void CampoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefonoKeyTyped

    public void iniciar () {
        
        if (hombre.isSelected() == true) {
            id_sexo = 1;
            sexo = hombre.getText();
        } else if (mujer.isSelected() == true) {
            id_sexo = 2;
            sexo = mujer.getText();
        } else if (otro.isSelected() == true) {
            id_sexo = 3;
            sexo = otro.getText();
        }
        
        if (CampoNombre.getText().trim().equals(Registro.nombre) && CampoApellido.getText().trim().equals(Registro.apellido) && CampoCorreo.getText().trim().equals(Registro.correo) && CampoFecha.getText().trim().equalsIgnoreCase(Registro.fecha) && CampoContrasenia.getText().trim().equals(Registro.contrasenia) && CampoPais.getSelectedIndex() == Registro.id_pais && CampoTelefono.getText().equals(Registro.telefono) && id_sexo == Registro.id_sexo && pic == false) {

            JOptionPane.showMessageDialog(null, "No se han realizado cambios", "", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } else if (CampoNombre.getText().length() == 0 || CampoApellido.getText().length() == 0 || CampoContrasenia.getText().length() == 0 || CampoCorreo.getText().length() == 0 || CampoFecha.getText().trim() == null) {
            
            JOptionPane.showMessageDialog(null, "¡Debes rellenar los campos más importantes!", "", JOptionPane.WARNING_MESSAGE);
        
        } else if (CampoPais.getSelectedIndex() == 0) {
            
            JOptionPane.showMessageDialog(null, "¡Debes rellenar los campos más importantes!", "", JOptionPane.WARNING_MESSAGE);   
        
        } else {
            
           fecha = CampoFecha.getText().trim();
            
           try {
                
               if (fecha.equals("")) {
                
               } else if (hombre.isSelected() == true || mujer.isSelected() == true || otro.isSelected() == true) {
                        
                   if (hombre.isSelected() == true) {
                         
                       id_sexo = 1;
                       sexo = hombre.getText();
                       
                   } else if (mujer.isSelected() == true) {
                   
                       id_sexo = 2;
                       sexo = mujer.getText();
                       
                   } else if (otro.isSelected() == true) {
                   
                       id_sexo = 3;
                       sexo = otro.getText();
                       
                   }     
                       
                       if (CampoCorreo.getText().contains("@") && CampoCorreo.getText().contains(".")){
                           
                           if (CampoFecha.getText().contains("-")) {
                               
                               if (CampoTelefono.getText().trim().matches("[0-9]+")) {
                                   
                                                         
                                   error1.setVisible(false);

                                   if (CampoTelefono.getText().trim().matches("[0-9]+")) {

                                       error3.setVisible(false);

                                       if (CampoContrasenia.getText().length() >= 6) {

                                           error2.setVisible(false);

                                           int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);

                                           if (msj == JOptionPane.YES_OPTION) {
                                               JOptionPane.showMessageDialog(null, "Su configuración ha sido actualizada", "", JOptionPane.INFORMATION_MESSAGE);
                                               correo = CampoCorreo.getText().trim();
                                               nombre = CampoNombre.getText().trim();
                                               apellido = CampoApellido.getText().trim();
                                               contrasenia = String.valueOf(CampoContrasenia.getPassword());
                                               fecha = CampoFecha.getText().trim();
                                               telefono = CampoTelefono.getText().trim();
                                               pais = (String) CampoPais.getSelectedItem();
                                               id_pais = (int) CampoPais.getSelectedIndex();
                                               this.dispose();
                                               
                                               try {
                                                   Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_cinemark", "root", "");
                                                   PreparedStatement pst = cn.prepareStatement("update usuarios set nombre = ?, apellido = ?, correo = ?, contrasenia = ?, telefono = ?, fecha = ?, pais = ?, sexo = ?, idpais = ?, idsexo = ?  where id = " + Login.ID);

                                                   pst.setString(1, nombre);
                                                   pst.setString(2, apellido);
                                                   pst.setString(3, correo);
                                                   pst.setString(4, contrasenia);
                                                   pst.setString(5, telefono);
                                                   pst.setString(6, fecha);
                                                   pst.setString(7, pais);
                                                   pst.setString(8, sexo);
                                                   pst.setInt(9, id_sexo);
                                                   pst.setInt(10, id_pais);
                                                   
                                                   pst.executeUpdate();

                                               } catch (Exception e) {

                                                   JOptionPane.showMessageDialog(null, "Error! " + e);

                                               }

                                           }
                                       } else {

                                           JOptionPane.showMessageDialog(null, "La contraseña debe tener un mínimo de 6 caracteres", "", JOptionPane.ERROR_MESSAGE);
                                           error2.setVisible(true);

                                       }

                                   } else {

                                       JOptionPane.showMessageDialog(null, "Error! Teléfono inválido", "", JOptionPane.ERROR_MESSAGE);
                                       error3.setVisible(true);
                                   }
                                   
                               } else {
                                   
                                   JOptionPane.showMessageDialog(null, "Error! Fecha incorrecta", "", JOptionPane.ERROR_MESSAGE);
                                   
                               }
                               
                           } else {
                               
                               JOptionPane.showMessageDialog(null, "Error! Fecha incorrecta", "", JOptionPane.ERROR_MESSAGE);
                               
                           }
                       
                   } else {
                       
                       JOptionPane.showMessageDialog(null, "Error! Correo inválido", "", JOptionPane.ERROR_MESSAGE);
                       error1.setVisible(true);
                   }   
                       
                   
                   
                } else {                       
                        JOptionPane.showMessageDialog(null, "¡Debes rellenar los campos más importantes", "", JOptionPane.WARNING_MESSAGE);
                    } 
                
            } catch (Exception ex) {
                
                JOptionPane.showMessageDialog(null, "¡Debes rellenar los campos más importantes! " + ex, "", JOptionPane.WARNING_MESSAGE);
            
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonCambiar;
    private rojeru_san.RSButton BotonCerrar;
    private rojeru_san.RSButtonRiple BotonContinuar;
    private rojeru_san.RSMTextFull CampoApellido;
    private rojeru_san.RSMPassView CampoContrasenia;
    private rojeru_san.RSMTextFull CampoCorreo;
    private rojeru_san.RSMTextFull CampoFecha;
    private rojeru_san.RSMTextFull CampoNombre;
    private javax.swing.JComboBox CampoPais;
    private rojeru_san.RSMTextFull CampoTelefono;
    private javax.swing.ButtonGroup GrupoSexo;
    public static javax.swing.JLabel Imagen;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JRadioButton hombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mujer;
    private javax.swing.JRadioButton otro;
    private javax.swing.JPanel panel;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    // End of variables declaration//GEN-END:variables
}
