/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Asientos extends javax.swing.JFrame {
    private Color newColor;

    public static int tickets;
    
    public Asientos() {
        initComponents();
        setLocationRelativeTo(null);

        tickets = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAtras = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        marco2 = new rojeru_san.RSPanelShadow();
        boton1 = new javax.swing.JButton();
        boton24 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton40 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        boton41 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton12 = new javax.swing.JButton();
        boton14 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton21 = new javax.swing.JButton();
        boton43 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton19 = new javax.swing.JButton();
        boton18 = new javax.swing.JButton();
        boton17 = new javax.swing.JButton();
        boton42 = new javax.swing.JButton();
        boton28 = new javax.swing.JButton();
        boton38 = new javax.swing.JButton();
        boton20 = new javax.swing.JButton();
        boton23 = new javax.swing.JButton();
        boton16 = new javax.swing.JButton();
        boton34 = new javax.swing.JButton();
        boton31 = new javax.swing.JButton();
        boton25 = new javax.swing.JButton();
        boton29 = new javax.swing.JButton();
        boton37 = new javax.swing.JButton();
        boton36 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        boton44 = new javax.swing.JButton();
        boton11 = new javax.swing.JButton();
        boton45 = new javax.swing.JButton();
        tv = new javax.swing.JPanel();
        marco3 = new rojeru_san.RSPanelShadow();
        disponible = new javax.swing.JLabel();
        BotonDisponible = new javax.swing.JButton();
        ocupado = new javax.swing.JLabel();
        BotonOcupado = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        BotonCerrar1 = new rojeru_san.RSButton();
        BotonMenu = new javax.swing.JLabel();
        BotonCerrar = new rojeru_san.RSButton();
        BotonMinimizar = new rojeru_san.RSButton();
        marco = new rojeru_san.RSPanelShadow();
        BotonAsientos1 = new rsbuttoncustom.RSButtonCustom();
        BotonSnackBar1 = new rsbuttoncustom.RSButtonCustom();
        BotonSesiones1 = new rsbuttoncustom.RSButtonCustom();
        BotonPago1 = new rsbuttoncustom.RSButtonCustom();
        BotonMinimizar1 = new rojeru_san.RSButton();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (2).png"))); // NOI18N
        BotonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseExited(evt);
            }
        });
        getContentPane().add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setMinimumSize(new java.awt.Dimension(0, 0));
        panel2.setPreferredSize(new java.awt.Dimension(940, 560));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marco2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setBackground(new java.awt.Color(251, 176, 52));
        boton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton1.setBorderPainted(false);
        boton1.setContentAreaFilled(false);
        boton1.setOpaque(true);
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton1MouseExited(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        marco2.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 70, 70));

        boton24.setBackground(new java.awt.Color(251, 176, 52));
        boton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton24.setBorderPainted(false);
        boton24.setContentAreaFilled(false);
        boton24.setOpaque(true);
        boton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton24MouseExited(evt);
            }
        });
        marco2.add(boton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 70, 70));

        boton5.setBackground(new java.awt.Color(251, 176, 52));
        boton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton5.setBorderPainted(false);
        boton5.setContentAreaFilled(false);
        boton5.setOpaque(true);
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton5MouseExited(evt);
            }
        });
        marco2.add(boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 70, 70));

        boton8.setBackground(new java.awt.Color(251, 176, 52));
        boton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton8.setBorderPainted(false);
        boton8.setContentAreaFilled(false);
        boton8.setOpaque(true);
        boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton8MouseExited(evt);
            }
        });
        marco2.add(boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 70, 70));

        boton40.setBackground(new java.awt.Color(251, 176, 52));
        boton40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton40.setBorderPainted(false);
        boton40.setContentAreaFilled(false);
        boton40.setOpaque(true);
        boton40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton40MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton40MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton40MouseExited(evt);
            }
        });
        marco2.add(boton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 70, 70));

        boton10.setBackground(new java.awt.Color(251, 176, 52));
        boton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton10.setBorderPainted(false);
        boton10.setContentAreaFilled(false);
        boton10.setOpaque(true);
        boton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton10MouseExited(evt);
            }
        });
        marco2.add(boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 70, 70));

        boton41.setBackground(new java.awt.Color(251, 176, 52));
        boton41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton41.setBorderPainted(false);
        boton41.setContentAreaFilled(false);
        boton41.setOpaque(true);
        boton41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton41MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton41MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton41MouseExited(evt);
            }
        });
        marco2.add(boton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 70, 70));

        boton7.setBackground(new java.awt.Color(251, 176, 52));
        boton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton7.setBorderPainted(false);
        boton7.setContentAreaFilled(false);
        boton7.setOpaque(true);
        boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton7MouseExited(evt);
            }
        });
        marco2.add(boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 70, 70));

        boton2.setBackground(new java.awt.Color(251, 176, 52));
        boton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton2.setBorderPainted(false);
        boton2.setContentAreaFilled(false);
        boton2.setOpaque(true);
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton2MouseExited(evt);
            }
        });
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        marco2.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 70, 70));

        boton12.setBackground(new java.awt.Color(251, 176, 52));
        boton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton12.setBorderPainted(false);
        boton12.setContentAreaFilled(false);
        boton12.setOpaque(true);
        boton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton12MouseExited(evt);
            }
        });
        marco2.add(boton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 70, 70));

        boton14.setBackground(new java.awt.Color(251, 176, 52));
        boton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton14.setBorderPainted(false);
        boton14.setContentAreaFilled(false);
        boton14.setOpaque(true);
        boton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton14MouseExited(evt);
            }
        });
        marco2.add(boton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 180, 70, 70));

        boton3.setBackground(new java.awt.Color(251, 176, 52));
        boton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton3.setBorderPainted(false);
        boton3.setContentAreaFilled(false);
        boton3.setOpaque(true);
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton3MouseExited(evt);
            }
        });
        marco2.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 70, 70));

        boton21.setBackground(new java.awt.Color(251, 176, 52));
        boton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton21.setBorderPainted(false);
        boton21.setContentAreaFilled(false);
        boton21.setOpaque(true);
        boton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton21MouseExited(evt);
            }
        });
        marco2.add(boton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 70, 70));

        boton43.setBackground(new java.awt.Color(251, 176, 52));
        boton43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton43.setBorderPainted(false);
        boton43.setContentAreaFilled(false);
        boton43.setOpaque(true);
        boton43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton43MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton43MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton43MouseExited(evt);
            }
        });
        marco2.add(boton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 70, 70));

        boton4.setBackground(new java.awt.Color(251, 176, 52));
        boton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton4.setBorderPainted(false);
        boton4.setContentAreaFilled(false);
        boton4.setOpaque(true);
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton4MouseExited(evt);
            }
        });
        marco2.add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 70, 70));

        boton19.setBackground(new java.awt.Color(251, 176, 52));
        boton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton19.setBorderPainted(false);
        boton19.setContentAreaFilled(false);
        boton19.setOpaque(true);
        boton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton19MouseExited(evt);
            }
        });
        marco2.add(boton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 70, 70));

        boton18.setBackground(new java.awt.Color(251, 176, 52));
        boton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton18.setBorderPainted(false);
        boton18.setContentAreaFilled(false);
        boton18.setOpaque(true);
        boton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton18MouseExited(evt);
            }
        });
        marco2.add(boton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 70, 70));

        boton17.setBackground(new java.awt.Color(251, 176, 52));
        boton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton17.setBorderPainted(false);
        boton17.setContentAreaFilled(false);
        boton17.setOpaque(true);
        boton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton17MouseExited(evt);
            }
        });
        marco2.add(boton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 70, 70));

        boton42.setBackground(new java.awt.Color(251, 176, 52));
        boton42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton42.setBorderPainted(false);
        boton42.setContentAreaFilled(false);
        boton42.setOpaque(true);
        boton42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton42MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton42MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton42MouseExited(evt);
            }
        });
        marco2.add(boton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 70, 70));

        boton28.setBackground(new java.awt.Color(251, 176, 52));
        boton28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton28.setBorderPainted(false);
        boton28.setContentAreaFilled(false);
        boton28.setOpaque(true);
        boton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton28MouseExited(evt);
            }
        });
        marco2.add(boton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 70, 70));

        boton38.setBackground(new java.awt.Color(251, 176, 52));
        boton38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton38.setBorderPainted(false);
        boton38.setContentAreaFilled(false);
        boton38.setOpaque(true);
        boton38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton38MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton38MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton38MouseExited(evt);
            }
        });
        marco2.add(boton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 300, 70, 70));

        boton20.setBackground(new java.awt.Color(251, 176, 52));
        boton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton20.setBorderPainted(false);
        boton20.setContentAreaFilled(false);
        boton20.setOpaque(true);
        boton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton20MouseExited(evt);
            }
        });
        marco2.add(boton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 70, 70));

        boton23.setBackground(new java.awt.Color(251, 176, 52));
        boton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton23.setBorderPainted(false);
        boton23.setContentAreaFilled(false);
        boton23.setOpaque(true);
        boton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton23MouseExited(evt);
            }
        });
        marco2.add(boton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 420, 70, 70));

        boton16.setBackground(new java.awt.Color(251, 176, 52));
        boton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton16.setBorderPainted(false);
        boton16.setContentAreaFilled(false);
        boton16.setOpaque(true);
        boton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton16MouseExited(evt);
            }
        });
        marco2.add(boton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 70, 70));

        boton34.setBackground(new java.awt.Color(251, 176, 52));
        boton34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton34.setBorderPainted(false);
        boton34.setContentAreaFilled(false);
        boton34.setOpaque(true);
        boton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton34MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton34MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton34MouseExited(evt);
            }
        });
        marco2.add(boton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 70, 70));

        boton31.setBackground(new java.awt.Color(251, 176, 52));
        boton31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton31.setBorderPainted(false);
        boton31.setContentAreaFilled(false);
        boton31.setOpaque(true);
        boton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton31MouseExited(evt);
            }
        });
        marco2.add(boton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 70, 70));

        boton25.setBackground(new java.awt.Color(251, 176, 52));
        boton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton25.setBorderPainted(false);
        boton25.setContentAreaFilled(false);
        boton25.setOpaque(true);
        boton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton25MouseExited(evt);
            }
        });
        boton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton25ActionPerformed(evt);
            }
        });
        marco2.add(boton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 70, 70));

        boton29.setBackground(new java.awt.Color(251, 176, 52));
        boton29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton29.setBorderPainted(false);
        boton29.setContentAreaFilled(false);
        boton29.setOpaque(true);
        boton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton29MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton29MouseExited(evt);
            }
        });
        marco2.add(boton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 70, 70));

        boton37.setBackground(new java.awt.Color(251, 176, 52));
        boton37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton37.setBorderPainted(false);
        boton37.setContentAreaFilled(false);
        boton37.setOpaque(true);
        boton37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton37MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton37MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton37MouseExited(evt);
            }
        });
        marco2.add(boton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 300, 70, 70));

        boton36.setBackground(new java.awt.Color(251, 176, 52));
        boton36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton36.setBorderPainted(false);
        boton36.setContentAreaFilled(false);
        boton36.setOpaque(true);
        boton36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton36MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton36MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton36MouseExited(evt);
            }
        });
        marco2.add(boton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 70, 70));

        jButton3.setBackground(new java.awt.Color(251, 176, 52));
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        marco2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 70, 70));

        jButton4.setBackground(new java.awt.Color(251, 176, 52));
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        marco2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 420, 70, 70));

        jButton5.setBackground(new java.awt.Color(251, 176, 52));
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        marco2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 540, 70, 70));

        boton44.setBackground(new java.awt.Color(251, 176, 52));
        boton44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton44.setBorderPainted(false);
        boton44.setContentAreaFilled(false);
        boton44.setEnabled(false);
        boton44.setOpaque(true);
        boton44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton44MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton44MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton44MouseExited(evt);
            }
        });
        marco2.add(boton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 70, 70));

        boton11.setBackground(new java.awt.Color(251, 176, 52));
        boton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton11.setBorderPainted(false);
        boton11.setContentAreaFilled(false);
        boton11.setEnabled(false);
        boton11.setOpaque(true);
        boton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton11MouseExited(evt);
            }
        });
        marco2.add(boton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 70, 70));

        boton45.setBackground(new java.awt.Color(251, 176, 52));
        boton45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton45.setBorderPainted(false);
        boton45.setContentAreaFilled(false);
        boton45.setEnabled(false);
        boton45.setOpaque(true);
        boton45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton45MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton45MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton45MouseExited(evt);
            }
        });
        marco2.add(boton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 60, 70, 70));

        tv.setBackground(new java.awt.Color(0, 0, 0));
        marco2.add(tv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 1010, 30));

        marco3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        disponible.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        disponible.setText("DISPONIBLE ");
        marco3.add(disponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 320, 50));

        BotonDisponible.setBackground(new java.awt.Color(251, 176, 52));
        BotonDisponible.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonDisponible.setContentAreaFilled(false);
        BotonDisponible.setOpaque(true);
        BotonDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDisponibleActionPerformed(evt);
            }
        });
        marco3.add(BotonDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        ocupado.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        ocupado.setText("OCUPADO");
        marco3.add(ocupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, 50));

        BotonOcupado.setBackground(new java.awt.Color(181, 18, 27));
        BotonOcupado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonOcupado.setContentAreaFilled(false);
        BotonOcupado.setEnabled(false);
        BotonOcupado.setOpaque(true);
        marco3.add(BotonOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 30));

        marco2.add(marco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 110));

        panel2.add(marco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1470, 750));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 1490, 770));

        BotonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next (1).png"))); // NOI18N
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseExited(evt);
            }
        });
        getContentPane().add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 580, 140, -1));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar1.setBorder(null);
        BotonCerrar1.setText("X");
        BotonCerrar1.setBorderPainted(false);
        BotonCerrar1.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar1.setFocusable(false);
        BotonCerrar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrar1MouseClicked(evt);
            }
        });
        panel.add(BotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        panel.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setBorder(null);
        BotonCerrar.setText("X");
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar.setFocusable(false);
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        panel.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4504, 0, 60, 80));

        BotonMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar.setBorder(null);
        BotonMinimizar.setText("—");
        BotonMinimizar.setBorderPainted(false);
        BotonMinimizar.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar.setFocusable(false);
        BotonMinimizar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizarMouseEntered(evt);
            }
        });
        BotonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizarActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4437, 0, 60, 80));

        marco.setForeground(new java.awt.Color(204, 4, 17));
        marco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAsientos1.setForeground(new java.awt.Color(181, 18, 27));
        BotonAsientos1.setText("ASIENTOS");
        BotonAsientos1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonAsientos1.setFocusPainted(false);
        BotonAsientos1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonAsientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 460, 140));

        BotonSnackBar1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSnackBar1.setText("SNACK BAR");
        BotonSnackBar1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonSnackBar1.setEnabled(false);
        BotonSnackBar1.setFocusPainted(false);
        BotonSnackBar1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonSnackBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 460, 140));

        BotonSesiones1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setText("SESIONES");
        BotonSesiones1.setColorMaterial(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setEnabled(false);
        BotonSesiones1.setFocusPainted(false);
        BotonSesiones1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonSesiones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSesiones1MouseClicked(evt);
            }
        });
        marco.add(BotonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 140));

        BotonPago1.setForeground(new java.awt.Color(181, 18, 27));
        BotonPago1.setText("PAGO ");
        BotonPago1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonPago1.setEnabled(false);
        BotonPago1.setFocusPainted(false);
        BotonPago1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, 450, 140));

        panel.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1900, 160));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 290));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1530, 720));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1530, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 340, 1530, 750));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 10, 1530, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    int i1=0, i2=0, i3=0, i4=0, i5=0, i6=0, i7=0, i8=0, i9=0, i10=0, i11=0, i12=0, I13=0, i14=0, i15=0, i16=0, i17=0, i18=0, i19=0, i20=0, i21=0, i22=0, i23=0, i24=0, i25=0, i26=0,
            i27=0, i28=0, i29=0, i30=0, i31=0, i32=0, i33=0, i34=0, i35=0, i36=0, i37=0, i38=0, i39=0, i40=0, i41=0, i42=0, i43=0, i44=0, i45=0;
    
    
    
    private void boton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton25ActionPerformed

    private void boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseClicked
        i8++;
        clicks(i8, boton8);        
        
        
    }//GEN-LAST:event_boton8MouseClicked

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
            
        i1++;
        if (clicks(i1, boton1)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }
        
    }//GEN-LAST:event_boton1MouseClicked

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
        i2++;
        if (clicks(i2, boton2)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }
    }//GEN-LAST:event_boton2MouseClicked

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        
    }//GEN-LAST:event_boton1ActionPerformed

    private void BotonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseClicked

        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea volver?", "", JOptionPane.YES_NO_OPTION);
        
        if (msj == JOptionPane.YES_OPTION){
            
            tickets = 0;
            Sesion.horario = null;
            Sesion.fecha = null;
            
            Sesion ventana = new Sesion();
            ventana.setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_BotonAtrasMouseClicked

    private void BotonSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseClicked

        
        if (tickets == 0) {
            
            JOptionPane.showMessageDialog(null, "¡Debes seleccionar los asientos a escoger!", "", JOptionPane.ERROR_MESSAGE);
            
        } else {
            
       
        SnackBar ventana = new SnackBar();
        ventana.setVisible(true);
        this.dispose();
        
        }
    }//GEN-LAST:event_BotonSiguienteMouseClicked

    private void BotonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseEntered
        
    }//GEN-LAST:event_BotonSiguienteMouseEntered

    private void BotonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseExited
        
    }//GEN-LAST:event_BotonSiguienteMouseExited

    private void BotonDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDisponibleActionPerformed

    private void BotonAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseEntered
        
    }//GEN-LAST:event_BotonAtrasMouseEntered

    private void BotonAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseExited
        
    }//GEN-LAST:event_BotonAtrasMouseExited

    private void boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseClicked
        i3++;
        if (clicks(i3, boton3)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }
    }//GEN-LAST:event_boton3MouseClicked

    private void boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseClicked
        i4++;
        if (clicks(i4, boton4)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }      // TODO add your handling code here:
    }//GEN-LAST:event_boton4MouseClicked

    private void boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseClicked
        i5++;
        if (clicks(i5, boton5)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }     // TODO add your handling code here:
    }//GEN-LAST:event_boton5MouseClicked

    private void boton45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton45MouseClicked
        i45++;
        if (clicks(i45, boton45)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton45MouseClicked

    private void boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseClicked
        i7++;
        if (clicks(i7, boton7)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_boton7MouseClicked

    private void boton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton11MouseClicked
        i11++;
        if (clicks(i11, boton11)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton11MouseClicked

    private void boton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton10MouseClicked
        i10++;
        if (clicks(i1, boton1)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton10MouseClicked

    private void boton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton12MouseClicked
        i12++;
        clicks(i12, boton12);        // TODO add your handling code here:
    }//GEN-LAST:event_boton12MouseClicked

    private void boton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton20MouseClicked
        i20++;
        clicks(i10, boton10);        // TODO add your handling code here:
    }//GEN-LAST:event_boton20MouseClicked

    private void boton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton19MouseClicked
        i19++;
        if (clicks(i19, boton19)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }      // TODO add your handling code here:
    }//GEN-LAST:event_boton19MouseClicked

    private void boton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton14MouseClicked
        i14++;
        if (clicks(i14, boton14)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_boton14MouseClicked

    private void boton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton16MouseClicked
        i16++;
        if (clicks(i16, boton16)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton16MouseClicked

    private void boton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton23MouseClicked
        i23++;
        if (clicks(i23, boton23)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }     // TODO add your handling code here:
    }//GEN-LAST:event_boton23MouseClicked

    private void boton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton17MouseClicked
        i17++;
        if (clicks(i17, boton17)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton17MouseClicked

    private void boton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton18MouseClicked
        i18++;
        if (clicks(i18, boton18)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }      // TODO add your handling code here:
    }//GEN-LAST:event_boton18MouseClicked

    private void boton34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton34MouseClicked
        i34++;
        if (clicks(i34, boton34)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton34MouseClicked

    private void boton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton28MouseClicked
        i28++;
        if (clicks(i28, boton28)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton28MouseClicked

    private void boton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton21MouseClicked
        i21++;
        if (clicks(i21, boton21)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton21MouseClicked

    private void boton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton29MouseClicked
        i29++;
        if (clicks(i29, boton29)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }      // TODO add your handling code here:
    }//GEN-LAST:event_boton29MouseClicked

    private void boton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton31MouseClicked
        i31++;
        if (clicks(i31, boton31)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_boton31MouseClicked

    private void boton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton25MouseClicked
        i25++;
        if (clicks(i25, boton25)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_boton25MouseClicked

    private void boton40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton40MouseClicked
        i40++;
        if (clicks(i40, boton40)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }      // TODO add your handling code here:
    }//GEN-LAST:event_boton40MouseClicked

    private void boton41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton41MouseClicked
        i41++;
         if (clicks(i41, boton41)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_boton41MouseClicked

    private void boton36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton36MouseClicked
        i36++;
        if (clicks(i36, boton36)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton36MouseClicked

    private void boton37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton37MouseClicked
        i37++;
        if (clicks(i37, boton37)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton37MouseClicked

    private void boton38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton38MouseClicked
        i38++;
        if (clicks(i38, boton38)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton38MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        i5++;
        if (clicks(i5, jButton5)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        i3++;
        if (clicks(i3, jButton3)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void boton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton24MouseClicked
        i24++;
        if (clicks(i24, boton24)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton24MouseClicked

    private void boton42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton42MouseClicked
        i42++;
        if (clicks(i42, boton42)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton42MouseClicked

    private void boton43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton43MouseClicked
        i43++;
        if (clicks(i43, boton43)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton43MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        i4++;
         if (clicks(i4, jButton4)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void boton44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton44MouseClicked
        i44++;
        if (clicks(i44, boton44)) {
            
            tickets--;
            
        } else {
            
            tickets++;
            
        }       // TODO add your handling code here:
    }//GEN-LAST:event_boton44MouseClicked

    private void boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseEntered

        if (clicks(i1, boton1)) {
            ocupado(this.boton1);
        } else {
            
        }
    }//GEN-LAST:event_boton1MouseEntered

    private void boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseEntered
        if (clicks(i2, boton2)) {
            ocupado(this.boton2);
        } else {
            
        }
    }//GEN-LAST:event_boton2MouseEntered

    private void boton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseEntered
        if (clicks(i3, boton3)) {
            ocupado(this.boton3);
        } else {
            
        }
    }//GEN-LAST:event_boton3MouseEntered

    private void boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseEntered
        if (clicks(i4, boton4)) {
            ocupado(this.boton4);
        } else {
            
        }
    }//GEN-LAST:event_boton4MouseEntered

    private void boton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseEntered
        if (clicks(i5, boton5)) {
            ocupado(this.boton5);
        } else {
            
        }
    }//GEN-LAST:event_boton5MouseEntered

    private void boton45MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton45MouseEntered
        if (clicks(i45, boton45)) {
            ocupado(this.boton45);
        } else {
            
        }
    }//GEN-LAST:event_boton45MouseEntered

    private void boton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseEntered
        if (clicks(i7, boton7)) {
            ocupado(this.boton7);
        } else {
            
        }
    }//GEN-LAST:event_boton7MouseEntered

    private void boton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseEntered
        if (clicks(i8, boton8)) {
            ocupado(this.boton8);
        } else {
            
        }
    }//GEN-LAST:event_boton8MouseEntered

    private void boton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton11MouseEntered
        if (clicks(i11, boton11)) {
            ocupado(this.boton11);
        } else {
            
        }
    }//GEN-LAST:event_boton11MouseEntered

    private void boton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton10MouseEntered
        if (clicks(i10, boton10)) {
            ocupado(this.boton10);
        } else {
            
        }
    }//GEN-LAST:event_boton10MouseEntered

    private void boton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton12MouseEntered
        if (clicks(i12, boton12)) {
            ocupado(this.boton12);
        } else {
            
        }
    }//GEN-LAST:event_boton12MouseEntered

    private void boton20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton20MouseEntered
        if (clicks(i20, boton20)) {
            ocupado(this.boton20);
        } else {
            
        }
    }//GEN-LAST:event_boton20MouseEntered

    private void boton19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton19MouseEntered
        if (clicks(i19, boton19)) {
            ocupado(this.boton19);
        } else {
            
        }
    }//GEN-LAST:event_boton19MouseEntered

    private void boton14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton14MouseEntered
        if (clicks(i14, boton14)) {
            ocupado(this.boton14);
        } else {
            
        }
    }//GEN-LAST:event_boton14MouseEntered

    private void boton16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton16MouseEntered
        if (clicks(i16, boton16)) {
            ocupado(this.boton16);
        } else {
            
        }
    }//GEN-LAST:event_boton16MouseEntered

    private void boton23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton23MouseEntered
        if (clicks(i23, boton23)) {
            ocupado(this.boton23);
        } else {
            
        }
    }//GEN-LAST:event_boton23MouseEntered

    private void boton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton17MouseEntered
        if (clicks(i17, boton17)) {
            ocupado(this.boton17);
        } else {
            
        }
    }//GEN-LAST:event_boton17MouseEntered

    private void boton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton18MouseEntered
        if (clicks(i18, boton18)) {
            ocupado(this.boton18);
        } else {
            
        }
    }//GEN-LAST:event_boton18MouseEntered

    private void boton34MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton34MouseEntered
        if (clicks(i34, boton34)) {
            ocupado(this.boton34);
        } else {
            
        }
    }//GEN-LAST:event_boton34MouseEntered

    private void boton28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton28MouseEntered
        if (clicks(i28, boton28)) {
            ocupado(this.boton28);
        } else {
            
        }
    }//GEN-LAST:event_boton28MouseEntered

    private void boton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton21MouseEntered
        if (clicks(i21, boton21)) {
            ocupado(this.boton21);
        } else {
            
        }
    }//GEN-LAST:event_boton21MouseEntered

    private void boton29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton29MouseEntered
        if (clicks(i29, boton29)) {
            ocupado(this.boton29);
        } else {
            
        }
    }//GEN-LAST:event_boton29MouseEntered

    private void boton31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton31MouseEntered
        if (clicks(i31, boton31)) {
            ocupado(this.boton31);
        } else {
            
        }
    }//GEN-LAST:event_boton31MouseEntered

    private void boton25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton25MouseEntered
        if (clicks(i25, boton25)) {
            ocupado(this.boton25);
        } else {
            
        }
    }//GEN-LAST:event_boton25MouseEntered

    private void boton40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton40MouseEntered
        if (clicks(i40, boton40)) {
            ocupado(this.boton40);
        } else {
            
        }
    }//GEN-LAST:event_boton40MouseEntered

    private void boton41MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton41MouseEntered
        if (clicks(i41, boton41)) {
            ocupado(this.boton41);
        } else {
            
        }
    }//GEN-LAST:event_boton41MouseEntered

    private void boton36MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton36MouseEntered
        if (clicks(i36, boton36)) {
            ocupado(this.boton36);
        } else {
            
        }
    }//GEN-LAST:event_boton36MouseEntered

    private void boton37MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton37MouseEntered
        if (clicks(i37, boton37)) {
            ocupado(this.boton37);
        } else {
            
        }
    }//GEN-LAST:event_boton37MouseEntered

    private void boton38MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton38MouseEntered
        if (clicks(i38, boton38)) {
            ocupado(this.boton38);
        } else {
            
        }
    }//GEN-LAST:event_boton38MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        if (clicks(i5, jButton5)) {
            ocupado(this.jButton5);
        } else {
            
        }
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        if (clicks(i3, jButton3)) {
            ocupado(this.jButton3);
        } else {
            
        }
    }//GEN-LAST:event_jButton3MouseEntered

    private void boton24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton24MouseEntered
        if (clicks(i24, boton24)) {
            ocupado(this.boton24);
        } else {
            
        }
    }//GEN-LAST:event_boton24MouseEntered

    private void boton42MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton42MouseEntered
        if (clicks(i42, boton42)) {
            ocupado(this.boton42);
        } else {
            
        }
    }//GEN-LAST:event_boton42MouseEntered

    private void boton43MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton43MouseEntered
        if (clicks(i43, boton43)) {
            ocupado(this.boton43);
        } else {
            
        }
    }//GEN-LAST:event_boton43MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        if (clicks(i4, jButton4)) {
            ocupado(this.jButton4);
        } else {
            
        }
    }//GEN-LAST:event_jButton4MouseEntered

    private void boton44MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton44MouseEntered
        if (clicks(i44, boton44)) {
            ocupado(this.boton44);
        } else {
            
        }
    }//GEN-LAST:event_boton44MouseEntered

    private void boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseExited
        if (clicks(i1, boton1)) {
            disponible(this.boton1);
        } else {
            
        }
    }//GEN-LAST:event_boton1MouseExited

    private void boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseExited
         if (clicks(i2, boton2)) {
            disponible(this.boton2);
        } else {
            
        }
    }//GEN-LAST:event_boton2MouseExited

    private void boton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseExited
          if (clicks(i3, boton3)) {
            disponible(this.boton3);
        } else {
            
        }
    }//GEN-LAST:event_boton3MouseExited

    private void boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseExited
            if (clicks(i4, boton4)) {
            disponible(this.boton4);
        } else {
            
        }
    }//GEN-LAST:event_boton4MouseExited

    private void boton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseExited
         if (clicks(i5, boton5)) {
            disponible(this.boton5);
        } else {
            
        }
    }//GEN-LAST:event_boton5MouseExited

    private void boton45MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton45MouseExited
        if (clicks(i45, boton45)) {
            disponible(this.boton45);
        } else {
            
        }
    }//GEN-LAST:event_boton45MouseExited

    private void boton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseExited
           if (clicks(i7, boton7)) {
            disponible(this.boton7);
        } else {
            
        }
    }//GEN-LAST:event_boton7MouseExited

    private void boton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseExited
        if (clicks(i8, boton8)) {
            disponible(this.boton8);
        } else {

        }
    }//GEN-LAST:event_boton8MouseExited

    private void boton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton11MouseExited
          if (clicks(i11, boton11)) {
            disponible(this.boton11);
        } else {
            
        }
    }//GEN-LAST:event_boton11MouseExited

    private void boton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton10MouseExited
        if (clicks(i10, boton10)) {
            disponible(this.boton10);
        } else {
            
        }
    }//GEN-LAST:event_boton10MouseExited

    private void boton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton12MouseExited
        if (clicks(i12, boton12)) {
            disponible(this.boton12);
        } else {
            
        }
    }//GEN-LAST:event_boton12MouseExited

    private void boton20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton20MouseExited
        if (clicks(i20, boton20)) {
            disponible(this.boton20);
        } else {
            
        }
    }//GEN-LAST:event_boton20MouseExited

    private void boton19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton19MouseExited
        if (clicks(i19, boton19)) {
            disponible(this.boton19);
        } else {
            
        }
    }//GEN-LAST:event_boton19MouseExited

    private void boton14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton14MouseExited
        if (clicks(i14, boton14)) {
            disponible(this.boton14);
        } else {
            
        }
    }//GEN-LAST:event_boton14MouseExited

    private void boton16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton16MouseExited
        if (clicks(i16, boton16)) {
            disponible(this.boton16);
        } else {
            
        }
    }//GEN-LAST:event_boton16MouseExited

    private void boton23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton23MouseExited
        if (clicks(i23, boton23)) {
            disponible(this.boton23);
        } else {
            
        }
    }//GEN-LAST:event_boton23MouseExited

    private void boton17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton17MouseExited
        if (clicks(i17, boton17)) {
            disponible(this.boton17);
        } else {
            
        }
    }//GEN-LAST:event_boton17MouseExited

    private void boton18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton18MouseExited
        if (clicks(i18, boton18)) {
            disponible(this.boton18);
        } else {
            
        }
    }//GEN-LAST:event_boton18MouseExited

    private void boton34MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton34MouseExited
        if (clicks(i34, boton34)) {
            disponible(this.boton34);
        } else {
            
        }
    }//GEN-LAST:event_boton34MouseExited

    private void boton28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton28MouseExited
        if (clicks(i28, boton28)) {
            disponible(this.boton28);
        } else {
            
        }
    }//GEN-LAST:event_boton28MouseExited

    private void boton21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton21MouseExited
        if (clicks(i21, boton21)) {
            disponible(this.boton21);
        } else {
            
        }
    }//GEN-LAST:event_boton21MouseExited

    private void boton29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton29MouseExited
        if (clicks(i29, boton29)) {
            disponible(this.boton29);
        } else {
            
        }
    }//GEN-LAST:event_boton29MouseExited

    private void boton31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton31MouseExited
        if (clicks(i31, boton31)) {
            disponible(this.boton31);
        } else {
            
        }
    }//GEN-LAST:event_boton31MouseExited

    private void boton25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton25MouseExited
        if (clicks(i25, boton25)) {
            disponible(this.boton25);
        } else {
            
        }
    }//GEN-LAST:event_boton25MouseExited

    private void boton40MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton40MouseExited
        if (clicks(i40, boton40)) {
            disponible(this.boton40);
        } else {
            
        }
    }//GEN-LAST:event_boton40MouseExited

    private void boton41MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton41MouseExited
        if (clicks(i41, boton41)) {
            disponible(this.boton41);
        } else {
            
        }
    }//GEN-LAST:event_boton41MouseExited

    private void boton36MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton36MouseExited
        if (clicks(i36, boton36)) {
            disponible(this.boton36);
        } else {
            
        }
    }//GEN-LAST:event_boton36MouseExited

    private void boton37MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton37MouseExited
        if (clicks(i37, boton37)) {
            disponible(this.boton37);
        } else {
            
        }
    }//GEN-LAST:event_boton37MouseExited

    private void boton38MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton38MouseExited
        if (clicks(i38, boton38)) {
            disponible(this.boton38);
        } else {
            
        }
    }//GEN-LAST:event_boton38MouseExited

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        if (clicks(i5, jButton5)) {
            disponible(this.jButton5);
        } else {
            
        }
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        if (clicks(i3, jButton3)) {
            disponible(this.jButton3);
        } else {
            
        }
    }//GEN-LAST:event_jButton3MouseExited

    private void boton24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton24MouseExited
        if (clicks(i24, boton24)) {
            disponible(this.boton24);
        } else {
            
        }
    }//GEN-LAST:event_boton24MouseExited

    private void boton42MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton42MouseExited
        if (clicks(i42, boton42)) {
            disponible(this.boton42);
        } else {
            
        }
    }//GEN-LAST:event_boton42MouseExited

    private void boton43MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton43MouseExited
        if (clicks(i43, boton43)) {
            disponible(this.boton43);
        } else {
            
        }
    }//GEN-LAST:event_boton43MouseExited

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        if (clicks(i4, jButton4)) {
            disponible(this.jButton4);
        } else {
            
        }
    }//GEN-LAST:event_jButton4MouseExited

    private void boton44MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton44MouseExited
        if (clicks(i44, boton44)) {
            disponible(this.boton44);
        } else {
            
        }
    }//GEN-LAST:event_boton44MouseExited

    private void BotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrar1MouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj == JOptionPane.YES_OPTION) {

            System.exit(0);

        }
    }//GEN-LAST:event_BotonCerrar1MouseClicked

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void BotonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizarMouseClicked

    private void BotonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizarMouseEntered

    private void BotonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizarActionPerformed

    private void BotonSesiones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesiones1MouseClicked

    }//GEN-LAST:event_BotonSesiones1MouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);
        
        if (msj==JOptionPane.YES_OPTION){
            
            tickets = 0;
            Sesion.fecha = null;
            Sesion.horario = null; 
            
            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();
            
        } 
    }//GEN-LAST:event_BotonMenuMouseClicked

    
    public boolean clicks(int i, JButton boton){
        
        if (i % 2 == 0) {

            boton.setBackground(new Color(251, 176, 52));
            boton.setBorderPainted(false);
   
            return true;

        } else {

            boton.setBackground(new Color(181, 18, 27));
            boton.setBorderPainted(true);
    
            return false;
            
        }
    
}
    

    
    public void disponible(JButton boton){
        
        boton.setBackground(new Color(251, 176, 52));
        
    }
    
    public void ocupado(JButton boton){
        
        boton.setBackground(new Color(181, 18, 27));
        
    }
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom BotonAsientos1;
    private javax.swing.JLabel BotonAtras;
    private rojeru_san.RSButton BotonCerrar;
    private rojeru_san.RSButton BotonCerrar1;
    private javax.swing.JButton BotonDisponible;
    private javax.swing.JLabel BotonMenu;
    private rojeru_san.RSButton BotonMinimizar;
    private rojeru_san.RSButton BotonMinimizar1;
    private javax.swing.JButton BotonOcupado;
    private rsbuttoncustom.RSButtonCustom BotonPago1;
    private rsbuttoncustom.RSButtonCustom BotonSesiones1;
    private javax.swing.JLabel BotonSiguiente;
    private rsbuttoncustom.RSButtonCustom BotonSnackBar1;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton11;
    private javax.swing.JButton boton12;
    private javax.swing.JButton boton14;
    private javax.swing.JButton boton16;
    private javax.swing.JButton boton17;
    private javax.swing.JButton boton18;
    private javax.swing.JButton boton19;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton20;
    private javax.swing.JButton boton21;
    private javax.swing.JButton boton23;
    private javax.swing.JButton boton24;
    private javax.swing.JButton boton25;
    private javax.swing.JButton boton28;
    private javax.swing.JButton boton29;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton31;
    private javax.swing.JButton boton34;
    private javax.swing.JButton boton36;
    private javax.swing.JButton boton37;
    private javax.swing.JButton boton38;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton40;
    private javax.swing.JButton boton41;
    private javax.swing.JButton boton42;
    private javax.swing.JButton boton43;
    private javax.swing.JButton boton44;
    private javax.swing.JButton boton45;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JLabel disponible;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private rojeru_san.RSPanelShadow marco;
    private rojeru_san.RSPanelShadow marco2;
    private rojeru_san.RSPanelShadow marco3;
    private javax.swing.JLabel ocupado;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel tv;
    // End of variables declaration//GEN-END:variables

    private Color NewColor(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
