/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import static frames.Registro.apellido;
import static frames.Registro.contrasenia;
import static frames.Registro.correo;
import static frames.Registro.fecha;
import static frames.Registro.nombre;
import static frames.Registro.pais;
import static frames.Registro.sexo;
import static frames.Registro.sexo;
import static frames.Registro.telefono;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Acer
 */
public class Condiciones extends javax.swing.JFrame {

    /**
     * Creates new form Condiciones
     */
    public Condiciones() {
        initComponents();
        setLocationRelativeTo(null);
        jTextArea1.setText("\n          TERMINOS Y CONDICIONES" + 		"\n\n          A.  PROHIBIDA SU VENTA O DISTRIBUCION SIN AUTORIZACION DE KUSTER." + 		"\n          B.  PROHIBIDA LA ALTERACION DEL CODIGO FUENTE O DISEÑO DE LAS INTERFACES GRAFICAS." +  		"\n          C.  KUSTER NO SE HACE RESPONSABLE DEL MAL USO DE ESTE SOFTWARE." + 		"\n\n          LOS ACUERDOS LEGALES EXPUESTOS ACONTINUACION RIGEN EL USO QUE USTED HAGA DE ESTE SOFTWARE" +  		"\n          (KUSTER Y SU AUTOR KUSTER JOAQUIN), NO SE RESPONSABILIZA DEL USO QUE USTED HAGA CON ESTE" + 		"\n          SOFTWARE Y SUS SERVICIOS. PARA ACEPTAR ESTOS TERMINOS HAGA CLICK EN (ACEPTO)" + 		"\n          SI USTED NO ACEPTA ESTOS TERMINOS, HAGA CLICK EN (NO ACEPTO) Y NO UTILIZE ESTE SOFTWARE." + 		"\n\n          PARA MAYOR INFORMACION SOBRE NUESTROS PRODUCTOS O SERVICIOS, POR FAVOR VISITE" +  		"\n          https://www.facebook.com/joaquin.kuster.3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        Check = new javax.swing.JCheckBox();
        BotonConfirmar = new rojeru_san.RSButtonRiple();
        BotonNoConfirmar = new rojeru_san.RSButtonRiple();
        AreaCondiciones = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        BotonCerrar = new rojeru_san.RSButton();
        BotonMinimizar1 = new rojeru_san.RSButton();
        fondo = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1530, 770));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(940, 560));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Check.setBackground(new java.awt.Color(255, 255, 255));
        Check.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        Check.setText("Acepto los términos y condicones ");
        Check.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckStateChanged(evt);
            }
        });
        Check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckMouseClicked(evt);
            }
        });
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });
        Check.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CheckKeyTyped(evt);
            }
        });
        panel.add(Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));

        BotonConfirmar.setBackground(new java.awt.Color(181, 18, 27));
        BotonConfirmar.setText("Confirmar");
        BotonConfirmar.setColorHover(new java.awt.Color(204, 4, 17));
        BotonConfirmar.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        BotonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonConfirmarMouseClicked(evt);
            }
        });
        panel.add(BotonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, 320, 120));

        BotonNoConfirmar.setBackground(new java.awt.Color(181, 18, 27));
        BotonNoConfirmar.setText("No Acepto");
        BotonNoConfirmar.setColorHover(new java.awt.Color(204, 4, 17));
        BotonNoConfirmar.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        BotonNoConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonNoConfirmarMouseClicked(evt);
            }
        });
        panel.add(BotonNoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, 330, 120));

        AreaCondiciones.setAutoscrolls(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto Bold", 3, 24)
        );
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        AreaCondiciones.setViewportView(jTextArea1);

        panel.add(AreaCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1170, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Bold", 3, 76));
        titulo.setText("Términos y Condiciones ");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1190, 630));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 1220, 850));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoMouseEntered(evt);
            }
        });
        panel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 140));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setBorder(null);
        BotonCerrar.setText("X");
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar.setFocusable(false);
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        panel1.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel1.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 140));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1560, 780));

        fondo1.setBackground(new java.awt.Color(255, 255, 255));
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 790));

        fondo2.setBackground(new java.awt.Color(255, 255, 255));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 1560, 820));

        fondo3.setBackground(new java.awt.Color(255, 255, 255));
        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 1390, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void CheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckMouseClicked

    private void CheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckStateChanged
        if (Check.isSelected() == true) {
            
            ok = true;
            
        } else {
            
            ok = false;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CheckStateChanged

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckActionPerformed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
            int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.ERROR_MESSAGE);

        if (msj == JOptionPane.YES_OPTION) {

            nombre = null;
            apellido = null;
            correo = null;
            contrasenia = null;
            telefono = null;
            fecha = null;
            pais = null;
            sexo = null;
            Registro.ruta = null; 
            Registro.ruta = null;
            Login ventana = new Login();
            ventana.setVisible(true);
            this.dispose();
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_logoMouseClicked

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){

            System.exit(0);

        }   ;
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    private void logoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoMouseEntered

    public boolean ok = false;
    
    private void BotonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConfirmarMouseClicked

        iniciar();
        
                   // TODO add your handling code here:
    }//GEN-LAST:event_BotonConfirmarMouseClicked

    private void BotonNoConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNoConfirmarMouseClicked

        if (ok == false)
        {
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a?", "", JOptionPane.YES_NO_OPTION);

            if (msj == JOptionPane.YES_OPTION) {

               
                nombre = null;
                contrasenia = null;
                Registro.ruta = null;
                Registro ventana = new Registro();
                ventana.setVisible(true);
                this.dispose();  
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_BotonNoConfirmarMouseClicked

    private void CheckKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CheckKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_CheckKeyTyped
	
    public void iniciar () {
        
        if (ok) {

            JOptionPane.showMessageDialog(null, "Su cuenta ha sido registrada", "", JOptionPane.INFORMATION_MESSAGE);

        try {

                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_cinemark", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into usuarios values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                pst.setString(1, "0");
                pst.setString(2, Registro.nombre);
                pst.setString(3, Registro.apellido);
                pst.setString(4, Registro.correo);
                pst.setString(5, Registro.contrasenia);
                pst.setString(6, Registro.telefono);
                pst.setString(7, Registro.fecha);
                pst.setString(8, Registro.pais);
                pst.setString(9, sexo);
                pst.setBoolean(10, false);
                pst.setBoolean(11, false);
                
            if (Registro.ruta == null) {

                pst.setString(12, "Sin foto de perfil");

            } else {    
                
                pst.setString(12, Registro.ruta);
            
            }
                pst.setInt(13, Registro.id_sexo);
                pst.setInt(14, Registro.id_pais);
                pst.setString(15, "Sin registrar");
                pst.setString(16, "Nulo");
                pst.setString(17, "Nulo");
                pst.setString(18, "Nulo");
                pst.executeUpdate();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Error al guardar: " + e);

            }
            
            Login ventana = new Login();
            ventana.setVisible(true);
            this.setVisible(false);

        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Condiciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AreaCondiciones;
    private rojeru_san.RSButton BotonCerrar;
    private rojeru_san.RSButtonRiple BotonConfirmar;
    private rojeru_san.RSButton BotonMinimizar1;
    private rojeru_san.RSButtonRiple BotonNoConfirmar;
    private javax.swing.JCheckBox Check;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
