/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JOptionPane;
import frames.*;

/**
 *
 * @author Acer
 */
public class FormasDePago extends javax.swing.JFrame {

    /**
     * Creates new form FormasDePago
     */
    
    public static boolean monedero;
    public static String metodo = null;
    
    public FormasDePago() {
        initComponents(); 
        setLocationRelativeTo(null);
        
            
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAtras = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        marco3 = new rojeru_san.RSPanelShadow();
        BotonPaypal = new javax.swing.JLabel();
        BotonTarjeta = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        BotonCerrar1 = new rojeru_san.RSButton();
        BotonMenu = new javax.swing.JLabel();
        BotonCerrar = new rojeru_san.RSButton();
        BotonMinimizar = new rojeru_san.RSButton();
        marco = new rojeru_san.RSPanelShadow();
        BotonAsientos1 = new rsbuttoncustom.RSButtonCustom();
        BotonSnackBar1 = new rsbuttoncustom.RSButtonCustom();
        BotonSesiones1 = new rsbuttoncustom.RSButtonCustom();
        BotonPago1 = new rsbuttoncustom.RSButtonCustom();
        BotonMinimizar1 = new rojeru_san.RSButton();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (2).png"))); // NOI18N
        BotonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseExited(evt);
            }
        });
        getContentPane().add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marco3MouseClicked(evt);
            }
        });
        marco3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonPaypal.setBackground(new java.awt.Color(255, 255, 255));
        BotonPaypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paypal (1).png"))); // NOI18N
        BotonPaypal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPaypalMouseClicked(evt);
            }
        });
        marco3.add(BotonPaypal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 520, 530));

        BotonTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        BotonTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credit-card (1).png"))); // NOI18N
        BotonTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonTarjeta.setOpaque(true);
        BotonTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTarjetaMouseClicked(evt);
            }
        });
        marco3.add(BotonTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 530));

        panel2.add(marco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1300, 680));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 1320, 700));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar1.setBorder(null);
        BotonCerrar1.setText("X");
        BotonCerrar1.setBorderPainted(false);
        BotonCerrar1.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar1.setFocusable(false);
        BotonCerrar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrar1MouseClicked(evt);
            }
        });
        panel.add(BotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        panel.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setBorder(null);
        BotonCerrar.setText("X");
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar.setFocusable(false);
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        panel.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4504, 0, 60, 80));

        BotonMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar.setBorder(null);
        BotonMinimizar.setText("—");
        BotonMinimizar.setBorderPainted(false);
        BotonMinimizar.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar.setFocusable(false);
        BotonMinimizar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizarMouseEntered(evt);
            }
        });
        BotonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizarActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4437, 0, 60, 80));

        marco.setForeground(new java.awt.Color(204, 4, 17));
        marco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAsientos1.setForeground(new java.awt.Color(181, 18, 27));
        BotonAsientos1.setText("ASIENTOS");
        BotonAsientos1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonAsientos1.setEnabled(false);
        BotonAsientos1.setFocusPainted(false);
        BotonAsientos1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonAsientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 460, 140));

        BotonSnackBar1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSnackBar1.setText("SNACK BAR");
        BotonSnackBar1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonSnackBar1.setEnabled(false);
        BotonSnackBar1.setFocusPainted(false);
        BotonSnackBar1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonSnackBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 460, 140));

        BotonSesiones1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setText("SESIONES");
        BotonSesiones1.setColorMaterial(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setEnabled(false);
        BotonSesiones1.setFocusPainted(false);
        BotonSesiones1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonSesiones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSesiones1MouseClicked(evt);
            }
        });
        marco.add(BotonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 140));

        BotonPago1.setForeground(new java.awt.Color(181, 18, 27));
        BotonPago1.setText("PAGO ");
        BotonPago1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonPago1.setFocusPainted(false);
        BotonPago1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, 450, 140));

        panel.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1900, 160));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 290));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 1530, 720));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1530, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 330, 1530, 750));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1530, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTarjetaMouseClicked

        if (monedero) {

            int msj = JOptionPane.showConfirmDialog(null, "¿Desea realizar la compra con su forma de pago registrada?", "", JOptionPane.YES_NO_OPTION);

            if (msj == JOptionPane.YES_OPTION) {

                this.dispose();
                Loading ventana = new Loading(new Ticket());
                ventana.setVisible(true);

            } else {

                Tarjeta ventana = new Tarjeta();
                ventana.setVisible(true);
                this.dispose();

            }
        } else {
            
            Tarjeta ventana = new Tarjeta();
            ventana.setVisible(true);
            this.dispose();
    
        }
        
    }//GEN-LAST:event_BotonTarjetaMouseClicked

    private void BotonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseClicked

        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea volver?", "", JOptionPane.YES_NO_OPTION);

        if (msj == JOptionPane.YES_OPTION){

            SnackBar.combo1 = 0;
            SnackBar.combo2 = 0;
            SnackBar.combo3 = 0;
            SnackBar.combo4 = 0;

            SnackBar ventana = new SnackBar();
            ventana.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_BotonAtrasMouseClicked

    private void BotonAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseEntered

    }//GEN-LAST:event_BotonAtrasMouseEntered

    private void BotonAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseExited

    }//GEN-LAST:event_BotonAtrasMouseExited

    private void marco3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marco3MouseClicked
      
    }//GEN-LAST:event_marco3MouseClicked

    private void BotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrar1MouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj == JOptionPane.YES_OPTION) {

            System.exit(0);

        }
    }//GEN-LAST:event_BotonCerrar1MouseClicked

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){

            SnackBar.combo1 = 0;
            SnackBar.combo2 = 0;
            SnackBar.combo3 = 0;
            SnackBar.combo4 = 0;

            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_BotonMenuMouseClicked

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void BotonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizarMouseClicked

    private void BotonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizarMouseEntered

    private void BotonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizarActionPerformed

    private void BotonSesiones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesiones1MouseClicked

    }//GEN-LAST:event_BotonSesiones1MouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    private void BotonPaypalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPaypalMouseClicked

        if (monedero) {

            int msj = JOptionPane.showConfirmDialog(null, "¿Desea realizar la compra con su forma de pago registrada?", "", JOptionPane.YES_NO_OPTION);

            if (msj == JOptionPane.YES_OPTION) {

                this.dispose();
                Loading ventana = new Loading(new Ticket());
                ventana.setVisible(true);

            } else {

                Paypal ventana = new Paypal();
                ventana.setVisible(true);
                this.dispose();

            }
        } else {
                
            this.dispose();
            Paypal ventana = new Paypal();
            ventana.setVisible(true);
            
        }
        
    }//GEN-LAST:event_BotonPaypalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormasDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormasDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormasDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormasDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormasDePago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom BotonAsientos1;
    private javax.swing.JLabel BotonAtras;
    private rojeru_san.RSButton BotonCerrar;
    private rojeru_san.RSButton BotonCerrar1;
    private javax.swing.JLabel BotonMenu;
    private rojeru_san.RSButton BotonMinimizar;
    private rojeru_san.RSButton BotonMinimizar1;
    private rsbuttoncustom.RSButtonCustom BotonPago1;
    private javax.swing.JLabel BotonPaypal;
    private rsbuttoncustom.RSButtonCustom BotonSesiones1;
    private rsbuttoncustom.RSButtonCustom BotonSnackBar1;
    private javax.swing.JLabel BotonTarjeta;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private rojeru_san.RSPanelShadow marco;
    private rojeru_san.RSPanelShadow marco3;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables

    private void setLocatioRelative(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
