/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import frames.*;
import AppPackage.AnimationClass;
import static frames.Lobby.BotonPremium;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class NotFound extends javax.swing.JFrame {

    /**
     * Creates new form NotFound
     */
    public NotFound() {
        initComponents();

        if (Premium.premium) {

            BotonPremium.setEnabled(false);

        } else {

            BotonPremium.setEnabled(true);

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRendererPanel1 = new org.jdesktop.swing.animation.rendering.JRendererPanel();
        facebook = new javax.swing.JLabel();
        instagram = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        BotonAjustes = new javax.swing.JLabel();
        BotonInternet1 = new javax.swing.JLabel();
        BotonPremium = new javax.swing.JLabel();
        BotonCerrar = new javax.swing.JLabel();
        BotonHome1 = new javax.swing.JLabel();
        BotonMaps1 = new javax.swing.JLabel();
        logo_menu = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        BotonBuscar = new javax.swing.JLabel();
        BotonUsuario = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        BotonMenu = new javax.swing.JLabel();
        CampoBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        error404 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRendererPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jRendererPanel1.setOpaque(false);
        jRendererPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        facebook.setBackground(new java.awt.Color(255, 255, 255));
        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ico-footer-facebook.png"))); // NOI18N
        facebook.setEnabled(false);
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facebookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facebookMouseExited(evt);
            }
        });
        jRendererPanel1.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 260, -1));

        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ico-footer-instagram_1.png"))); // NOI18N
        instagram.setEnabled(false);
        instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                instagramMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                instagramMouseExited(evt);
            }
        });
        jRendererPanel1.add(instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 260, 280));

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ico-footer-twitter.png"))); // NOI18N
        twitter.setEnabled(false);
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                twitterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                twitterMouseExited(evt);
            }
        });
        jRendererPanel1.add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 260, 260));

        getContentPane().add(jRendererPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 160, 290, 890));

        BotonAjustes.setBackground(new java.awt.Color(195, 8, 16));
        BotonAjustes.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        BotonAjustes.setForeground(new java.awt.Color(255, 255, 255));
        BotonAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools.png"))); // NOI18N
        BotonAjustes.setText("AJUSTES ");
        BotonAjustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonAjustes.setOpaque(true);
        BotonAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAjustesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAjustesMouseExited(evt);
            }
        });
        getContentPane().add(BotonAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 780, 900, 100));

        BotonInternet1.setBackground(new java.awt.Color(195, 8, 16));
        BotonInternet1.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        BotonInternet1.setForeground(new java.awt.Color(255, 255, 255));
        BotonInternet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonInternet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wifi.png"))); // NOI18N
        BotonInternet1.setText("ACERCA DE ");
        BotonInternet1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonInternet1.setOpaque(true);
        BotonInternet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonInternet1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonInternet1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonInternet1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonInternet1MousePressed(evt);
            }
        });
        getContentPane().add(BotonInternet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 680, 900, 100));

        BotonPremium.setBackground(new java.awt.Color(195, 8, 16));
        BotonPremium.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        BotonPremium.setForeground(new java.awt.Color(255, 255, 255));
        BotonPremium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonPremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vip.png"))); // NOI18N
        BotonPremium.setText("PREMIUM ");
        BotonPremium.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonPremium.setOpaque(true);
        BotonPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPremiumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonPremiumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonPremiumMouseExited(evt);
            }
        });
        getContentPane().add(BotonPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 880, 900, 100));

        BotonCerrar.setBackground(new java.awt.Color(195, 8, 16));
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        BotonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/errorr.png"))); // NOI18N
        BotonCerrar.setText("CERRAR SESIÓN");
        BotonCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonCerrar.setOpaque(true);
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseExited(evt);
            }
        });
        getContentPane().add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 980, 900, 100));

        BotonHome1.setBackground(new java.awt.Color(195, 8, 16));
        BotonHome1.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        BotonHome1.setForeground(new java.awt.Color(255, 255, 255));
        BotonHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (5).png"))); // NOI18N
        BotonHome1.setText("HOME ");
        BotonHome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonHome1.setOpaque(true);
        BotonHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHome1MouseExited(evt);
            }
        });
        BotonHome1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                BotonHome1ComponentHidden(evt);
            }
        });
        getContentPane().add(BotonHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 480, 900, 100));

        BotonMaps1.setBackground(new java.awt.Color(195, 8, 16));
        BotonMaps1.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        BotonMaps1.setForeground(new java.awt.Color(255, 255, 255));
        BotonMaps1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonMaps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa1.png"))); // NOI18N
        BotonMaps1.setText("UBICACIÓN");
        BotonMaps1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonMaps1.setOpaque(true);
        BotonMaps1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMaps1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMaps1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMaps1MouseExited(evt);
            }
        });
        getContentPane().add(BotonMaps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 580, 900, 100));

        logo_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cinemark-vector-logo.png"))); // NOI18N
        getContentPane().add(logo_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1000, 0, 890, -1));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseClicked(evt);
            }
        });
        BotonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BotonBuscarKeyTyped(evt);
            }
        });
        panel1.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 0, -1, 140));

        BotonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (3).png"))); // NOI18N
        BotonUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonUsuarioMouseClicked(evt);
            }
        });
        panel1.add(BotonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, -1, 140));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        panel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 780, 140));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu (2).png"))); // NOI18N
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        panel1.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 140));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 140));

        CampoBusqueda.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        CampoBusqueda.setForeground(new java.awt.Color(204, 204, 204));
        CampoBusqueda.setText("Digite una película...");
        CampoBusqueda.setSelectionColor(new java.awt.Color(181, 18, 27));
        CampoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoBusquedaMouseClicked(evt);
            }
        });
        CampoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBusquedaActionPerformed(evt);
            }
        });
        CampoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(CampoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, -100, 550, 100));

        jLabel1.setFont(new java.awt.Font("Roboto Bold", 3, 76));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No se encontraron resultados para su búsqueda ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 760, 1680, 70));

        error404.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/404-not-found-error-page-examples (1).png"))); // NOI18N
        getContentPane().add(error404, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 2370, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseClicked
        AnimationClass buscar = new AnimationClass();
        buscar.jTextFieldYDown(-100, 140, 10, 5, CampoBusqueda);

        AnimationClass buscarr = new AnimationClass();
        buscarr.jTextFieldYUp(140, -100, 10, 5, CampoBusqueda);
    }//GEN-LAST:event_BotonBuscarMouseClicked

    private void BotonBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotonBuscarKeyTyped

    }//GEN-LAST:event_BotonBuscarKeyTyped

    private void BotonUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonUsuarioMouseClicked
        Perfil dialog = new Perfil(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_BotonUsuarioMouseClicked

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked

        if (Premium.premium) {

            BotonPremium.setEnabled(false);

        } else {

            BotonPremium.setEnabled(true);

        }

        AnimationClass menu = new AnimationClass();
        menu.jLabelXRight(10, 900, 2, 10, BotonMenu);

        AnimationClass home = new AnimationClass();
        home.jLabelXRight(-1000, 0, 2, 10, BotonHome1);

        AnimationClass maps = new AnimationClass();
        maps.jLabelXRight(-1000, 0, 2, 10, BotonMaps1);

        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-1000, 0, 2, 10, BotonInternet1);

        AnimationClass ajustes = new AnimationClass();
        ajustes.jLabelXRight(-1000, 0, 2, 10, BotonAjustes);

        AnimationClass premium = new AnimationClass();
        premium.jLabelXRight(-1000, 0, 2, 10, BotonPremium);

        AnimationClass close = new AnimationClass();
        close.jLabelXRight(-1000, 0, 2, 10, BotonCerrar);

        AnimationClass logo1 = new AnimationClass();
        logo1.jLabelXRight(-1000, 0, 2, 10, logo_menu);

        AnimationClass menu2 = new AnimationClass();
        menu2.jLabelXLeft(900, 10, 2, 10, BotonMenu);

        AnimationClass home2 = new AnimationClass();
        home2.jLabelXLeft(0, -1000, 4, 10, BotonHome1);

        AnimationClass maps2 = new AnimationClass();
        maps2.jLabelXLeft(0, -1000, 4, 10, BotonMaps1);

        AnimationClass internet2 = new AnimationClass();
        internet2.jLabelXLeft(0, -1000, 4, 10, BotonInternet1);

        AnimationClass ajustes2 = new AnimationClass();
        ajustes2.jLabelXLeft(0, -1000, 4, 10, BotonAjustes);

        AnimationClass premium2 = new AnimationClass();
        premium2.jLabelXLeft(0, -1000, 4, 10, BotonPremium);

        AnimationClass close2 = new AnimationClass();
        close2.jLabelXLeft(0, -1000, 4, 10, BotonCerrar);

        AnimationClass logo2 = new AnimationClass();
        logo2.jLabelXLeft(0, -1000, 2, 10, logo_menu);

    }//GEN-LAST:event_BotonMenuMouseClicked

    private void CampoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoBusquedaMouseClicked
        // TODO add your handling code here:
        CampoBusqueda.setText("");
        CampoBusqueda.setForeground(Color.black);
    }//GEN-LAST:event_CampoBusquedaMouseClicked

    private void CampoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBusquedaActionPerformed

    private void CampoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBusquedaKeyTyped
        // TODO add your handling code here:
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == KeyEvent.VK_ENTER) {

            buscar(CampoBusqueda.getText());

        }
    }//GEN-LAST:event_CampoBusquedaKeyTyped

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/joaquin.kuster.3"));
        } catch (URISyntaxException ex){
            System.out.println(ex);
        } catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_facebookMouseClicked

    private void facebookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseEntered
        facebook.setEnabled(true);
    }//GEN-LAST:event_facebookMouseEntered

    private void facebookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseExited
        facebook.setEnabled(false);
    }//GEN-LAST:event_facebookMouseExited

    private void instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/joaquin_kuster/?hl=es-la"));
        } catch (URISyntaxException ex){
            System.out.println(ex);
        } catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_instagramMouseClicked

    private void instagramMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseEntered
        instagram.setEnabled(true);
    }//GEN-LAST:event_instagramMouseEntered

    private void instagramMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseExited
        instagram.setEnabled(false);
    }//GEN-LAST:event_instagramMouseExited

    private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://twitter.com/Emanuel16664715"));
        } catch (URISyntaxException ex){
            System.out.println(ex);
        } catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_twitterMouseClicked

    private void twitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseEntered
        twitter.setEnabled(true);
    }//GEN-LAST:event_twitterMouseEntered

    private void twitterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseExited
        twitter.setEnabled(false);
    }//GEN-LAST:event_twitterMouseExited

    private void BotonAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAjustesMouseClicked
        Ajustes dialog = new Ajustes(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_BotonAjustesMouseClicked

    private void BotonAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAjustesMouseEntered
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/tools2.png"));
        BotonAjustes.setIcon(image);
        BotonAjustes.setBackground(new Color(181, 18, 27));
    }//GEN-LAST:event_BotonAjustesMouseEntered

    private void BotonAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAjustesMouseExited
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/tools.png"));
        BotonAjustes.setIcon(image);
        BotonAjustes.setBackground(new Color(195, 8, 16));
    }//GEN-LAST:event_BotonAjustesMouseExited

    private void BotonInternet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInternet1MouseClicked
        AnimationClass ig = new AnimationClass();
        ig.jLabelXLeft(300, 0, 10, 15, instagram);

        AnimationClass tw = new AnimationClass();
        tw.jLabelXLeft(300, 0, 10, 15, twitter);

        AnimationClass fc = new AnimationClass();
        fc.jLabelXLeft(300, 0, 10, 15, facebook);

        AnimationClass ig2 = new AnimationClass();
        ig2.jLabelXRight(0, 300, 10, 15, instagram);

        AnimationClass tw2 = new AnimationClass();
        tw2.jLabelXRight(0, 300, 10, 15, twitter);

        AnimationClass fc2 = new AnimationClass();
        fc2.jLabelXRight(0, 300, 10, 15, facebook);

    }//GEN-LAST:event_BotonInternet1MouseClicked

    private void BotonInternet1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInternet1MouseEntered
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/wifi2.png"));
        BotonInternet1.setIcon(image);
        BotonInternet1.setBackground(new Color(181, 18, 27));
    }//GEN-LAST:event_BotonInternet1MouseEntered

    private void BotonInternet1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInternet1MouseExited
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/wifi.png"));
        BotonInternet1.setIcon(image);
        BotonInternet1.setBackground(new Color(195, 8, 16));
    }//GEN-LAST:event_BotonInternet1MouseExited

    private void BotonInternet1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInternet1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInternet1MousePressed

    private void BotonPremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPremiumMouseClicked

        if (Premium.premium) {
        } else {
            Premium dialog = new Premium(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_BotonPremiumMouseClicked

    private void BotonPremiumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPremiumMouseEntered
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/vip2.png"));
        BotonPremium.setIcon(image);
        BotonPremium.setBackground(new Color(181, 18, 27));
    }//GEN-LAST:event_BotonPremiumMouseEntered

    private void BotonPremiumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPremiumMouseExited
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/vip.png"));
        BotonPremium.setIcon(image);
        BotonPremium.setBackground(new Color(195, 8, 16));
    }//GEN-LAST:event_BotonPremiumMouseExited

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked

        Login ventana = new Login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void BotonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseEntered
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/erorr2.png"));
        BotonCerrar.setIcon(image);
        BotonCerrar.setBackground(new Color(181, 18, 27));
    }//GEN-LAST:event_BotonCerrarMouseEntered

    private void BotonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseExited
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/errorr.png"));
        BotonCerrar.setIcon(image);
        BotonCerrar.setBackground(new Color(195, 8, 16));
    }//GEN-LAST:event_BotonCerrarMouseExited

    private void BotonHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHome1MouseClicked

        JOptionPane.showMessageDialog(null, "¡Ya estás en el Lobby!", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonHome1MouseClicked

    private void BotonHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHome1MouseEntered
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/homee2.png"));
        BotonHome1.setIcon(image);
        BotonHome1.setBackground(new Color(181, 18, 27));
    }//GEN-LAST:event_BotonHome1MouseEntered

    private void BotonHome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHome1MouseExited
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/homee.png"));
        BotonHome1.setIcon(image);
        BotonHome1.setBackground(new Color(195, 8, 16));
    }//GEN-LAST:event_BotonHome1MouseExited

    private void BotonHome1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BotonHome1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonHome1ComponentHidden

    private void BotonMaps1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMaps1MouseClicked
        Ubicacion dialog = new Ubicacion(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_BotonMaps1MouseClicked

    private void BotonMaps1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMaps1MouseEntered
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/mapa.png"));
        BotonMaps1.setIcon(image);
        BotonMaps1.setBackground(new Color(181, 18, 27));
    }//GEN-LAST:event_BotonMaps1MouseEntered

    private void BotonMaps1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMaps1MouseExited
        Icon image;
        image = new ImageIcon(getClass().getResource("/images/mapa1.png"));
        BotonMaps1.setIcon(image);
        BotonMaps1.setBackground(new Color(195, 8, 16));
    }//GEN-LAST:event_BotonMaps1MouseExited

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);
        
        if (msj == JOptionPane.YES_OPTION) {
            
            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();
            
        }
        
    }//GEN-LAST:event_logoMouseClicked

    public void buscar(String film){
        
            if (film.equalsIgnoreCase("frozen 2") || film.equalsIgnoreCase("frozen")) {
                
                Pelicula1 ventana = new Pelicula1();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("angry birds 2")  || film.equalsIgnoreCase("angry birds") || film.equalsIgnoreCase("angry") || film.equalsIgnoreCase("birds")) {
                
                Pelicula2 ventana = new Pelicula2();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("proyecto geminis") || film.equalsIgnoreCase("geminis") || film.equalsIgnoreCase("proyecto")) {
                
                Pelicula3 ventana = new Pelicula3();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("malefica")) {
                
                Pelicula4 ventana = new Pelicula4();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("joker") || film.equalsIgnoreCase("guason") || film.equalsIgnoreCase("coringa")) {
                
                Pelicula5 ventana = new Pelicula5();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("terminator") || film.equalsIgnoreCase("terminator destino oculto") || film.equalsIgnoreCase("terminator destino") || film.equalsIgnoreCase("terminator oculto")) {
                
                Pelicula6 ventana = new Pelicula6();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("star wars") || film.equalsIgnoreCase("star") || film.equalsIgnoreCase("wars") || film.equalsIgnoreCase("star wars episodio ix") || film.equalsIgnoreCase("episodio ix") || film.equalsIgnoreCase("star wars episodio") ||
                    film.equalsIgnoreCase("star wars ix")) {
                
                Pelicula7 ventana = new Pelicula7();
                ventana.setVisible(true);
                this.dispose();
                
            } else if (film.equalsIgnoreCase("cats 2") || film.equalsIgnoreCase("cats")) {
                
                Pelicula8 ventana = new Pelicula8();
                ventana.setVisible(true);
                this.dispose();
                
            } else {
                
                NotFound ventana = new NotFound();
                ventana.setVisible(true);
                this.dispose();
                
            }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotFound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAjustes;
    private javax.swing.JLabel BotonBuscar;
    private javax.swing.JLabel BotonCerrar;
    private javax.swing.JLabel BotonHome1;
    private javax.swing.JLabel BotonInternet1;
    private javax.swing.JLabel BotonMaps1;
    private javax.swing.JLabel BotonMenu;
    public static javax.swing.JLabel BotonPremium;
    private javax.swing.JLabel BotonUsuario;
    private javax.swing.JTextField CampoBusqueda;
    private javax.swing.JLabel error404;
    private javax.swing.JLabel facebook;
    private javax.swing.JLabel instagram;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swing.animation.rendering.JRendererPanel jRendererPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo_menu;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel twitter;
    // End of variables declaration//GEN-END:variables
}
