/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Paypal extends javax.swing.JFrame {

    /**
     * Creates new form Paypal
     */
    
    public static String nombre_paypal=null, contrasenia_paypal=null;
    
    public Paypal() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        CampoContrasenia = new rojeru_san.RSMPassView();
        clave = new javax.swing.JLabel();
        CampoCorreo = new rojeru_san.RSMTextFull();
        user = new javax.swing.JLabel();
        BotonIniciar = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        paypal_gif = new javax.swing.JLabel();
        BotonAtras = new rojeru_san.RSButton();
        panel = new javax.swing.JPanel();
        BotonCerrar1 = new rojeru_san.RSButton();
        BotonMenu = new javax.swing.JLabel();
        BotonMinimizar1 = new rojeru_san.RSButton();
        marco = new rojeru_san.RSPanelShadow();
        BotonAsientos1 = new rsbuttoncustom.RSButtonCustom();
        BotonSnackBar1 = new rsbuttoncustom.RSButtonCustom();
        BotonSesiones1 = new rsbuttoncustom.RSButtonCustom();
        BotonPago1 = new rsbuttoncustom.RSButtonCustom();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paypal-logo-preview.png"))); // NOI18N
        panel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 476, 141));

        CampoContrasenia.setToolTipText("");
        CampoContrasenia.setFont(new java.awt.Font("Roboto Bold", 3, 36)); // NOI18N
        CampoContrasenia.setPlaceholder("Contraseña");
        CampoContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoContraseniaKeyTyped(evt);
            }
        });
        panel2.add(CampoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 500, 100));

        clave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-key-24.png"))); // NOI18N
        panel2.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        CampoCorreo.setFont(new java.awt.Font("Roboto Bold", 3, 36)); // NOI18N
        CampoCorreo.setPlaceholder("Correo o telefono ");
        CampoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorreoActionPerformed(evt);
            }
        });
        CampoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCorreoKeyTyped(evt);
            }
        });
        panel2.add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 500, 90));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-24.png"))); // NOI18N
        panel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 30, 45));

        BotonIniciar.setText("Inciar Sesión ");
        BotonIniciar.setFocusable(false);
        BotonIniciar.setFont(new java.awt.Font("Roboto Bold", 3, 36)); // NOI18N
        BotonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIniciarMouseClicked(evt);
            }
        });
        panel2.add(BotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 310, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 660, 280));

        paypal_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comp_3.gif"))); // NOI18N
        panel2.add(paypal_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -260, 670, 1060));

        BotonAtras.setBackground(new java.awt.Color(255, 255, 255));
        BotonAtras.setBorder(null);
        BotonAtras.setText("<");
        BotonAtras.setBorderPainted(false);
        BotonAtras.setColorHover(new java.awt.Color(0, 112, 192));
        BotonAtras.setColorText(new java.awt.Color(0, 0, 0));
        BotonAtras.setFocusable(false);
        BotonAtras.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        BotonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseClicked(evt);
            }
        });
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });
        panel2.add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 80));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 1130, 600));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar1.setBorder(null);
        BotonCerrar1.setText("X");
        BotonCerrar1.setBorderPainted(false);
        BotonCerrar1.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar1.setFocusable(false);
        BotonCerrar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrar1MouseClicked(evt);
            }
        });
        panel.add(BotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        panel.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        marco.setForeground(new java.awt.Color(204, 4, 17));
        marco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAsientos1.setForeground(new java.awt.Color(181, 18, 27));
        BotonAsientos1.setText("ASIENTOS");
        BotonAsientos1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonAsientos1.setEnabled(false);
        BotonAsientos1.setFocusPainted(false);
        BotonAsientos1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonAsientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 460, 140));

        BotonSnackBar1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSnackBar1.setText("SNACK BAR");
        BotonSnackBar1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonSnackBar1.setEnabled(false);
        BotonSnackBar1.setFocusPainted(false);
        BotonSnackBar1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonSnackBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 460, 140));

        BotonSesiones1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setText("SESIONES");
        BotonSesiones1.setColorMaterial(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setEnabled(false);
        BotonSesiones1.setFocusPainted(false);
        BotonSesiones1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonSesiones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSesiones1MouseClicked(evt);
            }
        });
        marco.add(BotonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 140));

        BotonPago1.setForeground(new java.awt.Color(181, 18, 27));
        BotonPago1.setText("PAGO ");
        BotonPago1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonPago1.setFocusPainted(false);
        BotonPago1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, 450, 140));

        panel.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1900, 160));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 290));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 1530, 720));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1530, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 330, 1530, 750));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1530, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseClicked

        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea volver?", "", JOptionPane.YES_NO_OPTION);

        if (msj == JOptionPane.YES_OPTION){

            nombre_paypal = null;
            contrasenia_paypal = null;
            FormasDePago ventana = new FormasDePago();
            ventana.setVisible(true);
             this.dispose();

        }

    }//GEN-LAST:event_BotonAtrasMouseClicked

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void BotonIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIniciarMouseClicked
        
        iniciar();
        
    }//GEN-LAST:event_BotonIniciarMouseClicked

    public void iniciar () {
        
        if (CampoCorreo.getText().isEmpty() || CampoContrasenia.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "¡Debes rellenar todos los campos!", "", JOptionPane.WARNING_MESSAGE);
            
        } else {
            
            if (CampoCorreo.getText().contains("@") && CampoCorreo.getText().contains(".")) {
                   
                int msj = JOptionPane.showConfirmDialog(null, "¿Desea registrar su cuenta de Paypal?", "", JOptionPane.YES_NO_OPTION);

                if (msj == JOptionPane.YES_OPTION) {
                
                    msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);
                    
                    if (msj == JOptionPane.YES_OPTION) {
                    
                    nombre_paypal = (String)CampoCorreo.getText().trim();
                    contrasenia_paypal = (String)CampoContrasenia.getText().trim();
                    FormasDePago.monedero = true;
                    FormasDePago.metodo = "paypal";
                    
                        try {
                            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_cinemark", "root", "");
                            PreparedStatement pst = cn.prepareStatement("update usuarios set monedero = true, formadepago = 'paypal', nombre_paypal = ? where id = " + Login.ID);

                            pst.setString(1, CampoCorreo.getText().trim());
                            
                            pst.executeUpdate();

                        } catch (Exception e) {

                            JOptionPane.showMessageDialog(null, "Error! " + e);

                        }
                    
                    Loading ventana = new Loading(new Ticket());
                    ventana.setVisible(true);
                    this.dispose();
                    
                    }
                    
                    } else {

                    msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);

                    if (msj == JOptionPane.YES_OPTION) {

                        Loading ventana = new Loading(new Ticket());
                        ventana.setVisible(true);
                        this.dispose();

                    }
                    
                }
                
                
                    
                
                
            } else if (CampoCorreo.getText().trim().matches("[0-9]+")){
                
                int msj = JOptionPane.showConfirmDialog(null, "¿Desea registrar su cuenta de Paypal?", "", JOptionPane.YES_NO_OPTION);

                if (msj == JOptionPane.YES_OPTION) {
                
                    msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);
                    
                    if (msj == JOptionPane.YES_OPTION) {
                    
                    nombre_paypal = (String)CampoCorreo.getText().trim();
                    contrasenia_paypal = (String)CampoContrasenia.getText().trim();
                    FormasDePago.monedero = true;
                    FormasDePago.metodo = "paypal";
                    
                        try {
                            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_cinemark", "root", "");
                            PreparedStatement pst = cn.prepareStatement("update usuarios set monedero = true, formadepago = 'paypal', nombre_paypal = ? where id = " + Login.ID);

                            pst.setString(1, CampoCorreo.getText().trim());
                            
                            pst.executeUpdate();

                        } catch (Exception e) {

                            JOptionPane.showMessageDialog(null, "Error! " + e);

                        }
                    
                    Loading ventana = new Loading(new Ticket());
                    ventana.setVisible(true);
                    this.dispose();
                    
                    }
                    
                    } else {

                    msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);

                    if (msj == JOptionPane.YES_OPTION) {

                        Loading ventana = new Loading(new Ticket());
                        ventana.setVisible(true);
                        this.dispose();

                    }
                    
                }
                
                
                
            } else {
             
                JOptionPane.showMessageDialog(null, "Error! La cuenta ingresada no existe", "", JOptionPane.ERROR_MESSAGE);
   
            }
             
            
        }
        
    }
    
    private void BotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrar1MouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){
   
            System.exit(0);

        }   
    }//GEN-LAST:event_BotonCerrar1MouseClicked

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){

            nombre_paypal = null;
            contrasenia_paypal = null;

            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenuMouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    private void BotonSesiones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesiones1MouseClicked

    }//GEN-LAST:event_BotonSesiones1MouseClicked

    private void CampoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoActionPerformed

    private void CampoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCorreoKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoKeyTyped

    private void CampoContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoContraseniaKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseniaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paypal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paypal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paypal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paypal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paypal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom BotonAsientos1;
    private rojeru_san.RSButton BotonAtras;
    private rojeru_san.RSButton BotonCerrar1;
    private rojeru_san.RSButtonRiple BotonIniciar;
    private javax.swing.JLabel BotonMenu;
    private rojeru_san.RSButton BotonMinimizar1;
    private rsbuttoncustom.RSButtonCustom BotonPago1;
    private rsbuttoncustom.RSButtonCustom BotonSesiones1;
    private rsbuttoncustom.RSButtonCustom BotonSnackBar1;
    private rojeru_san.RSMPassView CampoContrasenia;
    private rojeru_san.RSMTextFull CampoCorreo;
    private javax.swing.JLabel clave;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private rojeru_san.RSPanelShadow marco;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel paypal_gif;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private void setRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
