/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Pelicula4 extends javax.swing.JFrame {
    
    /**
     * Creates new form Pelicula1
     */
    public Pelicula4() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        duracion = new javax.swing.JPanel();
        jLabelDuracion = new javax.swing.JLabel();
        tematica = new javax.swing.JPanel();
        jLabelTematica = new javax.swing.JLabel();
        publico = new javax.swing.JPanel();
        jLabelEdad = new javax.swing.JLabel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        sinopsis = new javax.swing.JPanel();
        jLabelSinopsis = new javax.swing.JLabel();
        BotonPrecios = new rojeru_san.RSButtonRiple();
        BotonHorarios = new rojeru_san.RSButtonRiple();
        panel2 = new javax.swing.JPanel();
        BotonTrailer = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        sala = new javax.swing.JLabel();
        estreno = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        BotonCerrar = new rojeru_san.RSButton();
        BotonMinimizar1 = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/005_m (1).jpg"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 170, -1, -1));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        duracion.setBackground(new java.awt.Color(255, 255, 255));
        duracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelDuracion.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        jLabelDuracion.setForeground(new java.awt.Color(181, 18, 27));
        jLabelDuracion.setText("1 : 37 min");

        javax.swing.GroupLayout duracionLayout = new javax.swing.GroupLayout(duracion);
        duracion.setLayout(duracionLayout);
        duracionLayout.setHorizontalGroup(
            duracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        duracionLayout.setVerticalGroup(
            duracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duracionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panel.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, 80));

        tematica.setBackground(new java.awt.Color(255, 255, 255));
        tematica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tematica.setToolTipText("");
        tematica.setFont(new java.awt.Font("Roboto Bold", 3, 20));

        jLabelTematica.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        jLabelTematica.setForeground(new java.awt.Color(181, 18, 27));
        jLabelTematica.setText("FANTASÍA");

        javax.swing.GroupLayout tematicaLayout = new javax.swing.GroupLayout(tematica);
        tematica.setLayout(tematicaLayout);
        tematicaLayout.setHorizontalGroup(
            tematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTematica, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        tematicaLayout.setVerticalGroup(
            tematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTematica, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        panel.add(tematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 190, 80));

        publico.setBackground(new java.awt.Color(255, 255, 255));
        publico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelEdad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        jLabelEdad.setForeground(new java.awt.Color(181, 18, 27));
        jLabelEdad.setText("10");
        jLabelEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout publicoLayout = new javax.swing.GroupLayout(publico);
        publico.setLayout(publicoLayout);
        publicoLayout.setHorizontalGroup(
            publicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publicoLayout.createSequentialGroup()
                .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        publicoLayout.setVerticalGroup(
            publicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel.add(publico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 50, 80));

        sinopsis.setBackground(new java.awt.Color(255, 255, 255));
        sinopsis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSinopsis.setFont(new java.awt.Font("Roboto Bold", 2, 24));
        jLabelSinopsis.setText("<html>La joven Maléfica crece para proteger su pacífico reino de los invasores, pero una terrible traición transforma su corazón puro en una piedra y la convierte en una criatura en busca de venganza.<html>");
        jLabelSinopsis.setToolTipText("");
        jLabelSinopsis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelSinopsis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sinopsis.add(jLabelSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1310, 150));

        rSPanelShadow1.add(sinopsis, java.awt.BorderLayout.PAGE_START);

        panel.add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 1320, 170));

        BotonPrecios.setBackground(new java.awt.Color(181, 18, 27));
        BotonPrecios.setText("Precios");
        BotonPrecios.setColorHover(new java.awt.Color(204, 4, 17));
        BotonPrecios.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPreciosMouseClicked(evt);
            }
        });
        panel.add(BotonPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 240, 350, 70));

        BotonHorarios.setBackground(new java.awt.Color(181, 18, 27));
        BotonHorarios.setText("Ver horarios ");
        BotonHorarios.setColorHover(new java.awt.Color(204, 4, 17));
        BotonHorarios.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHorariosMouseClicked(evt);
            }
        });
        panel.add(BotonHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 330, 350, 80));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1920, 440));

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonTrailer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/youtube (1).png"))); // NOI18N
        BotonTrailer.setEnabled(false);
        BotonTrailer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTrailerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonTrailerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonTrailerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonTrailerMousePressed(evt);
            }
        });
        panel2.add(BotonTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, -1, -1));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Roboto Bold", 3, 76));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("MALÉFICA");
        panel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 830, 90));

        sala.setBackground(new java.awt.Color(181, 18, 27));
        sala.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        sala.setForeground(new java.awt.Color(181, 18, 27));
        sala.setText("3D");
        panel2.add(sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, -1, -1));

        estreno.setFont(new java.awt.Font("Roboto Bold", 3, 20));
        estreno.setForeground(new java.awt.Color(181, 18, 27));
        estreno.setText("10-11-19");
        panel2.add(estreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1920, 520));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        panel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 140));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setBorder(null);
        BotonCerrar.setText("X");
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar.setFocusable(false);
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        panel1.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel1.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTrailerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTrailerMouseClicked

        try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=F3ElY7y5H90"));
        } catch (URISyntaxException ex){
            System.out.println(ex);
        } catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_BotonTrailerMouseClicked

    private void BotonTrailerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTrailerMouseEntered
        BotonTrailer.setEnabled(true);
    }//GEN-LAST:event_BotonTrailerMouseEntered

    private void BotonTrailerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTrailerMouseExited
        BotonTrailer.setEnabled(false);
    }//GEN-LAST:event_BotonTrailerMouseExited

    private void BotonTrailerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTrailerMousePressed

    }//GEN-LAST:event_BotonTrailerMousePressed

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){
   
            System.exit(0);

        }   ;
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    private void BotonHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHorariosMouseClicked
        
        Lobby.pelicula = "Maléfica";
        Sesion ventana = new Sesion();
        ventana.setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BotonHorariosMouseClicked

    private void BotonPreciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPreciosMouseClicked
        Precios dialog = new Precios(new javax.swing.JFrame(), true);
        dialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPreciosMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){

           Lobby.pelicula = null;
            
            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_logoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelicula4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelicula4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelicula4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelicula4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelicula4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton BotonCerrar;
    private rojeru_san.RSButtonRiple BotonHorarios;
    private rojeru_san.RSButton BotonMinimizar1;
    private rojeru_san.RSButtonRiple BotonPrecios;
    private javax.swing.JLabel BotonTrailer;
    private javax.swing.JPanel duracion;
    private javax.swing.JLabel estreno;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelSinopsis;
    private javax.swing.JLabel jLabelTematica;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel publico;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private javax.swing.JLabel sala;
    private javax.swing.JPanel sinopsis;
    private javax.swing.JPanel tematica;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
