/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JFrame;
import frames.*;
/**
 *
 * @author Acer
 */
public class Precios extends javax.swing.JDialog {

    /**
     * Creates new form Precios
     */
    public Precios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        jTextArea1.setSelectionStart(0);
        jTextArea1.setText("Cinemark 2D\n" +
"2do, 2do, 3ro, 3ro: R $ 24,00 (matiné) - R $ 26,00 (noche)\n" +
"4to, 4to: R $ 23.00 (matiné) - R $ 24.00 (noche)\n" +
"5to, 5to, 6to, 6to: R $ 30,00 (matiné) - R $ 32,00 (noche)\n" +
"Sáb, sáb, dom, dom, enmiendas y feriados, enmiendas y feriados: R $ 32.00 todo el día\n" +
"\n" +
"Cinemark 3D\n" +
"2do, 2do, 3ro, 3ro: R $ 29,00 (matiné) - R $ 31,00 (noche)\n" +
"4to, 4to: R $ 28,00 (matiné) - R $ 29,00 (noche)\n" +
"5to, 5to: R $ 37,00 (matiné) - R $ 38,00 (noche)\n" +
"Viernes, viernes: R $ 38,00 todo el día\n" +
"Sábado, sábado, domingo, domingo, enmiendas y feriados, enmiendas y feriados: R $ 37,00 (vencimiento) - R $ 38,00 (noche)\n" +
"\n" +
"* Promociones válidas en los días mencionados, excepto días festivos, modificaciones, preventas y estrenos (ver tabla actual).\n" +
"\n" +
"Los valores promocionales no se aplican a las salas Prime y D-BOX; para salas XD, consulte la tabla de películas. Promociones no acumulables y válidas indefinidamente.\n" +
"\n" +
"** Las vistas previas tienen el mismo valor de boleto de fin de semana nocturno.\n" +
"\n" +
"*** Las enmiendas y días festivos tienen el mismo valor de boleto de fin de semana (ver tabla actual).\n" +
"\n" +
"**** La preventa tiene el mismo valor de ticket el día de la sesión que se muestra, de acuerdo con el precio de lista vigente en la fecha de la sesión.\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonRiple4 = new rojeru_san.RSButtonRiple();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1406, 1020));
        setSize(new java.awt.Dimension(1406, 1020));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRiple4.setBackground(new java.awt.Color(204, 4, 17));
        rSButtonRiple4.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonRiple4.setText("X");
        rSButtonRiple4.setToolTipText("");
        rSButtonRiple4.setColorHover(new java.awt.Color(181, 18, 27));
        rSButtonRiple4.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N
        rSButtonRiple4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple4MouseClicked(evt);
            }
        });
        getContentPane().add(rSButtonRiple4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 100, 70));
        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1390, 1000));

        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto Bold", 3, 24)
        );
        jTextArea1.setRows(5);
        jTextArea1.setFocusTraversalPolicyProvider(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 1270, 860));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, 870));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple4MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private rojeru_san.RSButtonRiple rSButtonRiple4;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables

}