/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Premium extends javax.swing.JDialog {

    /**
     * Creates new form Premium
     */
    
    public static boolean premium;
    
    public Premium(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        rSButtonRiple4 = new rojeru_san.RSButtonRiple();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1609, 765));
        setSize(new java.awt.Dimension(1609, 765));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRiple2.setText("$330 / AL MES");
        rSButtonRiple2.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        rSButtonRiple2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple2MouseClicked(evt);
            }
        });
        getContentPane().add(rSButtonRiple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 450, 140));

        rSButtonRiple1.setText("$525 / AL MES");
        rSButtonRiple1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        rSButtonRiple1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple1MouseClicked(evt);
            }
        });
        getContentPane().add(rSButtonRiple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 580, 450, 140));

        rSButtonRiple3.setText("$550 / AL MES");
        rSButtonRiple3.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        rSButtonRiple3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple3MouseClicked(evt);
            }
        });
        getContentPane().add(rSButtonRiple3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 450, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        jLabel5.setText("1 MES");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 286, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 383, 10));

        jLabel6.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        jLabel6.setForeground(new java.awt.Color(0, 112, 192));
        jLabel6.setText("$525,00");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 286, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, 450, 530));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        jLabel3.setForeground(new java.awt.Color(0, 112, 192));
        jLabel3.setText("$3951,00");

        jLabel4.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        jLabel4.setText("12 MESES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 450, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        jLabel7.setText("3 MESES");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 286, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 383, 10));

        jLabel8.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        jLabel8.setForeground(new java.awt.Color(0, 112, 192));
        jLabel8.setText("$1645,00");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 286, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 450, 530));

        rSButtonRiple4.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple4.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonRiple4.setText("X");
        rSButtonRiple4.setToolTipText("");
        rSButtonRiple4.setColorHover(new java.awt.Color(204, 4, 17));
        rSButtonRiple4.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonRiple4.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N
        rSButtonRiple4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple4MouseClicked(evt);
            }
        });
        getContentPane().add(rSButtonRiple4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 0, 90, 50));
        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1590, 740));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 1600, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple4MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple4MouseClicked

    private void rSButtonRiple2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple2MouseClicked
        ObtenerPremium();
    }//GEN-LAST:event_rSButtonRiple2MouseClicked

    private void rSButtonRiple3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple3MouseClicked
        ObtenerPremium();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple3MouseClicked

    private void rSButtonRiple1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple1MouseClicked
        ObtenerPremium();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple1MouseClicked

    public void ObtenerPremium() {
        
        if (FormasDePago.monedero) {
            
            int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea realizar la compra?", "", JOptionPane.YES_NO_OPTION);
            
            if (msj == JOptionPane.YES_OPTION) {
                
                premium = true;
                
                JOptionPane.showMessageDialog(null, "Adquiriste suscripción Premium!\nDisfruta de un 50% de descuento en todas tus compras", "", JOptionPane.INFORMATION_MESSAGE);
                
                Lobby.BotonPremium.setEnabled(false);
                
                try {
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_cinemark", "root", "");
                    PreparedStatement pst = cn.prepareStatement("update usuarios set premium = true where id = " + Login.ID);

                    pst.executeUpdate();

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "Error! " + e);

                }
                
                this.dispose();
                
            }
            
        } else {
            
            JOptionPane.showMessageDialog(null, "No se registró ningua forma de pago", "", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    private rojeru_san.RSButtonRiple rSButtonRiple4;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables
}
