/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import static frames.FormasDePago.monedero;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */


public class SnackBar extends javax.swing.JFrame {

    /**
     * Creates new form SnackBar
     */
    
    
    public SnackBar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        marco2 = new rojeru_san.RSPanelShadow();
        spin3 = new javax.swing.JSpinner();
        spin2 = new javax.swing.JSpinner();
        spin4 = new javax.swing.JSpinner();
        spin1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonAtras = new javax.swing.JLabel();
        BotonSiguiente = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        BotonCerrar1 = new rojeru_san.RSButton();
        BotonMenu = new javax.swing.JLabel();
        BotonCerrar = new rojeru_san.RSButton();
        BotonMinimizar = new rojeru_san.RSButton();
        marco = new rojeru_san.RSPanelShadow();
        BotonAsientos1 = new rsbuttoncustom.RSButtonCustom();
        BotonSnackBar1 = new rsbuttoncustom.RSButtonCustom();
        BotonSesiones1 = new rsbuttoncustom.RSButtonCustom();
        BotonPago1 = new rsbuttoncustom.RSButtonCustom();
        BotonMinimizar1 = new rojeru_san.RSButton();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setPreferredSize(new java.awt.Dimension(940, 560));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marco2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spin3.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        marco2.add(spin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 90, 70));

        spin2.setFont(new java.awt.Font("Roboto Bold", 3, 48));
        marco2.add(spin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 90, 70));

        spin4.setFont(new java.awt.Font("Roboto Bold", 3, 48)
        );
        marco2.add(spin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 90, 70));

        spin1.setFont(new java.awt.Font("Roboto Bold", 3, 48)
        );
        marco2.add(spin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 200, 90, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/combobalde300x237.jpg"))); // NOI18N
        marco2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 240));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/combommsdoce300x237.jpg"))); // NOI18N
        marco2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 300, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/combomega300x237.jpg"))); // NOI18N
        marco2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/combofini300x237.jpg"))); // NOI18N
        marco2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 240));

        panel2.add(marco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 300));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/promo_responsive_62_.png"))); // NOI18N
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1330, 690));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 1330, 780));

        BotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (2).png"))); // NOI18N
        BotonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, -1));

        BotonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next (1).png"))); // NOI18N
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 610, -1, -1));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar1.setBorder(null);
        BotonCerrar1.setText("X");
        BotonCerrar1.setBorderPainted(false);
        BotonCerrar1.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar1.setFocusable(false);
        BotonCerrar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrar1MouseClicked(evt);
            }
        });
        panel.add(BotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        panel.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setBorder(null);
        BotonCerrar.setText("X");
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar.setFocusable(false);
        BotonCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        panel.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4504, 0, 60, 80));

        BotonMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar.setBorder(null);
        BotonMinimizar.setText("—");
        BotonMinimizar.setBorderPainted(false);
        BotonMinimizar.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar.setFocusable(false);
        BotonMinimizar.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizarMouseEntered(evt);
            }
        });
        BotonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizarActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4437, 0, 60, 80));

        marco.setForeground(new java.awt.Color(204, 4, 17));
        marco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAsientos1.setForeground(new java.awt.Color(181, 18, 27));
        BotonAsientos1.setText("ASIENTOS");
        BotonAsientos1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonAsientos1.setEnabled(false);
        BotonAsientos1.setFocusPainted(false);
        BotonAsientos1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonAsientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 460, 140));

        BotonSnackBar1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSnackBar1.setText("SNACK BAR");
        BotonSnackBar1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonSnackBar1.setFocusPainted(false);
        BotonSnackBar1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonSnackBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 460, 140));

        BotonSesiones1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setText("SESIONES");
        BotonSesiones1.setColorMaterial(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setEnabled(false);
        BotonSesiones1.setFocusPainted(false);
        BotonSesiones1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonSesiones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSesiones1MouseClicked(evt);
            }
        });
        marco.add(BotonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 140));

        BotonPago1.setForeground(new java.awt.Color(181, 18, 27));
        BotonPago1.setText("PAGO ");
        BotonPago1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonPago1.setEnabled(false);
        BotonPago1.setFocusPainted(false);
        BotonPago1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, 450, 140));

        panel.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1900, 160));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 290));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 1730, 790));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1530, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 330, 1530, 750));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1530, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int combo1 = 0, combo2 = 0, combo3 = 0, combo4 =0;
    
    private void BotonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseClicked
        
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea volver?", "", JOptionPane.YES_NO_OPTION);
        
        if (msj==JOptionPane.YES_OPTION){
            
            combo1 = 0;
            combo2 = 0;
            combo3 = 0;
            combo4=0;
            Asientos.tickets = 0;
            
            Asientos ventana = new Asientos();
            ventana.setVisible(true);
            this.dispose();
            
        } 
    }//GEN-LAST:event_BotonAtrasMouseClicked

    private void BotonSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseClicked

        combo1 = (int) spin1.getValue();
        combo2 = (int) spin2.getValue();
        combo3 = (int) spin3.getValue();
        combo4= (int) spin4.getValue();
        
        if ((combo1 <= 0) && (combo2 <= 0) && (combo3 <= 0) && (combo4 <= 0)) {
           
            int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que no desea comprar nada?", "", JOptionPane.YES_NO_OPTION);

            if (msj == JOptionPane.YES_OPTION) {

                FormasDePago ventana = new FormasDePago();
                ventana.setVisible(true);
                this.dispose();
                
                } 
                
            } else {
            
            FormasDePago ventana = new FormasDePago();
            ventana.setVisible(true);
            this.dispose();
            
        }

        
    }//GEN-LAST:event_BotonSiguienteMouseClicked

    private void BotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrar1MouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj == JOptionPane.YES_OPTION) {

            System.exit(0);

        }
    }//GEN-LAST:event_BotonCerrar1MouseClicked

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){

            combo1 = 0;
            combo2 = 0;
            combo3 = 0;
            combo4=0;
            Asientos.tickets=0;
            
            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_BotonMenuMouseClicked

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void BotonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizarMouseClicked

    private void BotonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizarMouseEntered

    private void BotonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizarActionPerformed

    private void BotonSesiones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesiones1MouseClicked

    }//GEN-LAST:event_BotonSesiones1MouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnackBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnackBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnackBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnackBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnackBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom BotonAsientos1;
    private javax.swing.JLabel BotonAtras;
    private rojeru_san.RSButton BotonCerrar;
    private rojeru_san.RSButton BotonCerrar1;
    private javax.swing.JLabel BotonMenu;
    private rojeru_san.RSButton BotonMinimizar;
    private rojeru_san.RSButton BotonMinimizar1;
    private rsbuttoncustom.RSButtonCustom BotonPago1;
    private rsbuttoncustom.RSButtonCustom BotonSesiones1;
    private javax.swing.JLabel BotonSiguiente;
    private rsbuttoncustom.RSButtonCustom BotonSnackBar1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private rojeru_san.RSPanelShadow marco;
    private rojeru_san.RSPanelShadow marco2;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JSpinner spin1;
    private javax.swing.JSpinner spin2;
    private javax.swing.JSpinner spin3;
    private javax.swing.JSpinner spin4;
    // End of variables declaration//GEN-END:variables
}
