/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Tarjeta extends javax.swing.JFrame {

    /**
     * Creates new form Tarjeta
     */
    
    public static String tipo;
    public static String numero, codigo;
    
    public Tarjeta() {
        initComponents();

        americanexpress.setVisible(false);
        visa.setVisible(false);
        dinnersclub.setVisible(false);
        mastercard.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        ComboTipo = new javax.swing.JComboBox();
        tipos = new javax.swing.JLabel();
        BotonSiguiente = new rojeru_san.RSButton();
        BotonSiguiente2 = new rojeru_san.RSButton();
        dinnersclub = new javax.swing.JLabel();
        visa = new javax.swing.JLabel();
        mastercard = new javax.swing.JLabel();
        americanexpress = new javax.swing.JLabel();
        CampoNumero = new rojeru_san.RSMTextFull();
        numeros = new javax.swing.JLabel();
        CampoCodigo = new rojeru_san.RSMTextFull();
        codigos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tarjeta_gif = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        BotonCerrar1 = new rojeru_san.RSButton();
        BotonMenu = new javax.swing.JLabel();
        BotonMinimizar1 = new rojeru_san.RSButton();
        marco = new rojeru_san.RSPanelShadow();
        BotonAsientos1 = new rsbuttoncustom.RSButtonCustom();
        BotonSnackBar1 = new rsbuttoncustom.RSButtonCustom();
        BotonSesiones1 = new rsbuttoncustom.RSButtonCustom();
        BotonPago1 = new rsbuttoncustom.RSButtonCustom();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setFont(new java.awt.Font("Roboto Bold", 3, 20));
        panel2.setPreferredSize(new java.awt.Dimension(940, 560));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboTipo.setEditable(true);
        ComboTipo.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona tipo de tarjeta", "MasterCard", "American Express", "Diners club", "VISA" }));
        ComboTipo.setToolTipText("");
        ComboTipo.setFocusable(false);
        ComboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTipoItemStateChanged(evt);
            }
        });
        ComboTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboTipoKeyTyped(evt);
            }
        });
        panel2.add(ComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 460, 50));

        tipos.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        tipos.setText("Tipo:");
        panel2.add(tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, 70));

        BotonSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setBorder(null);
        BotonSiguiente.setText("➝>");
        BotonSiguiente.setBorderPainted(false);
        BotonSiguiente.setColorHover(new java.awt.Color(79, 186, 111));
        BotonSiguiente.setColorText(new java.awt.Color(0, 0, 0));
        BotonSiguiente.setFocusable(false);
        BotonSiguiente.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseClicked(evt);
            }
        });
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        panel2.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 480, 110, 80));

        BotonSiguiente2.setBackground(new java.awt.Color(255, 255, 255));
        BotonSiguiente2.setBorder(null);
        BotonSiguiente2.setText("<");
        BotonSiguiente2.setBorderPainted(false);
        BotonSiguiente2.setColorHover(java.awt.Color.red);
        BotonSiguiente2.setColorText(new java.awt.Color(0, 0, 0));
        BotonSiguiente2.setFocusable(false);
        BotonSiguiente2.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        BotonSiguiente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSiguiente2MouseClicked(evt);
            }
        });
        BotonSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguiente2ActionPerformed(evt);
            }
        });
        panel2.add(BotonSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 110, 80));

        dinnersclub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinners-club.png"))); // NOI18N
        panel2.add(dinnersclub, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        visa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visa (1).png"))); // NOI18N
        panel2.add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        mastercard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mastercard.png"))); // NOI18N
        panel2.add(mastercard, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        americanexpress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/american-express.png"))); // NOI18N
        panel2.add(americanexpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        CampoNumero.setForeground(new java.awt.Color(0, 0, 0));
        CampoNumero.setBordeColorFocus(new java.awt.Color(153, 153, 153));
        CampoNumero.setFont(new java.awt.Font("Roboto Bold", 3, 36)); // NOI18N
        CampoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoNumeroKeyTyped(evt);
            }
        });
        panel2.add(CampoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 460, 50));

        numeros.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        numeros.setText("Número:");
        panel2.add(numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, 60));

        CampoCodigo.setForeground(new java.awt.Color(0, 0, 0));
        CampoCodigo.setBordeColorFocus(new java.awt.Color(153, 153, 153));
        CampoCodigo.setFont(new java.awt.Font("Roboto Bold", 3, 36)); // NOI18N
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        CampoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCodigoKeyTyped(evt);
            }
        });
        panel2.add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 470, 50));

        codigos.setFont(new java.awt.Font("Roboto Bold", 3, 36));
        codigos.setText("Código:");
        panel2.add(codigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 180, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la tarjeta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Bold", 3, 24)));
        panel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 800, 390));

        tarjeta_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loop_2.gif"))); // NOI18N
        panel2.add(tarjeta_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 660, 440));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 1370, 560));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar1.setBorder(null);
        BotonCerrar1.setText("X");
        BotonCerrar1.setBorderPainted(false);
        BotonCerrar1.setColorHover(new java.awt.Color(255, 0, 0));
        BotonCerrar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar1.setFocusable(false);
        BotonCerrar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrar1MouseClicked(evt);
            }
        });
        panel.add(BotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 80, 40));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cinemark.png"))); // NOI18N
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        panel.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        BotonMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonMinimizar1.setBorder(null);
        BotonMinimizar1.setText("—");
        BotonMinimizar1.setBorderPainted(false);
        BotonMinimizar1.setColorHover(new java.awt.Color(204, 204, 204));
        BotonMinimizar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonMinimizar1.setFocusable(false);
        BotonMinimizar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMinimizar1MouseEntered(evt);
            }
        });
        BotonMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizar1ActionPerformed(evt);
            }
        });
        panel.add(BotonMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 0, 60, 40));

        marco.setForeground(new java.awt.Color(204, 4, 17));
        marco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAsientos1.setForeground(new java.awt.Color(181, 18, 27));
        BotonAsientos1.setText("ASIENTOS");
        BotonAsientos1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonAsientos1.setEnabled(false);
        BotonAsientos1.setFocusPainted(false);
        BotonAsientos1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonAsientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 460, 140));

        BotonSnackBar1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSnackBar1.setText("SNACK BAR");
        BotonSnackBar1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonSnackBar1.setEnabled(false);
        BotonSnackBar1.setFocusPainted(false);
        BotonSnackBar1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonSnackBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 460, 140));

        BotonSesiones1.setForeground(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setText("SESIONES");
        BotonSesiones1.setColorMaterial(new java.awt.Color(181, 18, 27));
        BotonSesiones1.setEnabled(false);
        BotonSesiones1.setFocusPainted(false);
        BotonSesiones1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonSesiones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSesiones1MouseClicked(evt);
            }
        });
        marco.add(BotonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 140));

        BotonPago1.setForeground(new java.awt.Color(181, 18, 27));
        BotonPago1.setText("PAGO ");
        BotonPago1.setColorMaterial(new java.awt.Color(204, 4, 17));
        BotonPago1.setFocusPainted(false);
        BotonPago1.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        marco.add(BotonPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, 450, 140));

        panel.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1900, 160));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 290));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 1530, 720));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1530, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 330, 1530, 750));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1530, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseClicked

        iniciar();

    }//GEN-LAST:event_BotonSiguienteMouseClicked

    public void iniciar () {
        
        if (ComboTipo.getSelectedIndex() == 0) {
            
            JOptionPane.showMessageDialog(null, "¡Debes completar todos los campos!", "", JOptionPane.WARNING_MESSAGE);
            
        } else if (CampoNumero.getText().isEmpty() || CampoCodigo.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "¡Debes completar todos los campos!", "", JOptionPane.WARNING_MESSAGE);
            
        } else if (CampoNumero.getText().trim().matches("[0-9]+")){
            
            if (CampoCodigo.getText().trim().matches("[0-9]+")) {
                
                if (CampoNumero.getText().trim().length() >= 13 && CampoNumero.getText().trim().length() <= 19) {
                    
                    if (CampoCodigo.getText().trim().length() == 4) {
                        
                        int msj = JOptionPane.showConfirmDialog(null, "¿Desea registrar su tarjeta?", "", JOptionPane.YES_NO_OPTION);

                        if (msj == JOptionPane.YES_OPTION) {

                            msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);

                            if (msj == JOptionPane.YES_OPTION) {                           
                            
                            numero = (String)CampoNumero.getText().trim();
                            codigo = (String)CampoCodigo.getText().trim();
                            tipo = (String) ComboTipo.getSelectedItem();
                            FormasDePago.monedero = true;
                            FormasDePago.metodo = "tarjeta";
                            
                                try {
                                    
                                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_cinemark", "root", "");
                                    PreparedStatement pst = cn.prepareStatement("update usuarios set monedero = true, formadepago = 'tarjeta', numero_tarjeta = ?, tipo_tarjeta = ? where id = " + Login.ID);
                                    
                                    pst.setString(1, CampoNumero.getText().trim());
                                    pst.setString(2, (String)ComboTipo.getSelectedItem());
                                    
                                    pst.executeUpdate();
                                    
                                    
                                } catch (Exception e) {
                                
                                    JOptionPane.showMessageDialog(null, "Error! " + e);
                                    
                                }
                            
                                this.dispose();
                                Loading ventana = new Loading(new Ticket());
                                ventana.setVisible(true);

                            }
                            
                        } else {

                            msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea continuar?", "", JOptionPane.YES_NO_OPTION);

                            if (msj == JOptionPane.YES_OPTION) {                          
                            
                            FormasDePago.monedero = false;
                            this.dispose();
                            Loading ventana = new Loading(new Ticket());
                            ventana.setVisible(true);


                            }
                            
                        }
                        
                    } else {
                        
                        JOptionPane.showMessageDialog(null, "Error! Código de seguridad inválido", "", JOptionPane.ERROR_MESSAGE);
                        JOptionPane.showMessageDialog(null, "El código de seguridad debe tener un total de 4 cifras", "", JOptionPane.WARNING_MESSAGE);
                        
                    }
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Error! Numero de tarjeta inválido", "", JOptionPane.ERROR_MESSAGE);
                    JOptionPane.showMessageDialog(null, "El numero de tarjeta debe estar compuesto entre 13-19 cifras", "", JOptionPane.WARNING_MESSAGE);
                    
                }
                
            } else {
                
                JOptionPane.showMessageDialog(null, "Error! Código de seguridad inválido", "", JOptionPane.ERROR_MESSAGE);
                
            }
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Error! Numero de tarjeta inválido", "", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
    }
    
    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    private void BotonSesiones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesiones1MouseClicked

    }//GEN-LAST:event_BotonSesiones1MouseClicked

    private void BotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrar1MouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);

        if (msj==JOptionPane.YES_OPTION){
   
            System.exit(0);

        }   
    }//GEN-LAST:event_BotonCerrar1MouseClicked

    private void BotonMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizar1MouseClicked

    private void BotonMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMinimizar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1MouseEntered

    private void BotonMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMinimizar1ActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void BotonSiguiente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguiente2MouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro que desea volver?", "", JOptionPane.YES_NO_OPTION);

        if (msj == JOptionPane.YES_OPTION) {

            
            FormasDePago ventana = new FormasDePago();
            ventana.setVisible(true);
            this.dispose();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSiguiente2MouseClicked

    private void BotonSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguiente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSiguiente2ActionPerformed

    private void ComboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTipoItemStateChanged
        
        if (ComboTipo.getSelectedIndex() == 1) {
            
            mastercard.setVisible(true);
            americanexpress.setVisible(false);
            visa.setVisible(false);
            dinnersclub.setVisible(false);
           
        }else if (ComboTipo.getSelectedIndex() == 2) {
            
            americanexpress.setVisible(true);
            visa.setVisible(false);
            dinnersclub.setVisible(false);
            mastercard.setVisible(false);
            
        } else if (ComboTipo.getSelectedIndex() == 3) {
            
            dinnersclub.setVisible(true);
            americanexpress.setVisible(false);
            visa.setVisible(false);
            mastercard.setVisible(false);
            
        } else if (ComboTipo.getSelectedIndex() == 4) {
            
            visa.setVisible(true);       
            americanexpress.setVisible(false);
            dinnersclub.setVisible(false);
            mastercard.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_ComboTipoItemStateChanged

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        int msj = JOptionPane.showConfirmDialog(null, "¿Estás seguro/a que desea salir?", "", JOptionPane.YES_NO_OPTION);
        
        if (msj==JOptionPane.YES_OPTION){
            
            numero = null;
            codigo = null;
            tipo = null;

            Lobby ventana = new Lobby();
            ventana.setVisible(true);
            this.dispose();
            
        }         // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenuMouseClicked

    private void ComboTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboTipoKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoKeyTyped

    private void CampoNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNumeroKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroKeyTyped

    private void CampoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCodigoKeyTyped
        char cTeclaPresionada = evt.getKeyChar();

        if (cTeclaPresionada == java.awt.event.KeyEvent.VK_ENTER) {

            iniciar();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom BotonAsientos1;
    private rojeru_san.RSButton BotonCerrar1;
    private javax.swing.JLabel BotonMenu;
    private rojeru_san.RSButton BotonMinimizar1;
    private rsbuttoncustom.RSButtonCustom BotonPago1;
    private rsbuttoncustom.RSButtonCustom BotonSesiones1;
    private rojeru_san.RSButton BotonSiguiente;
    private rojeru_san.RSButton BotonSiguiente2;
    private rsbuttoncustom.RSButtonCustom BotonSnackBar1;
    private rojeru_san.RSMTextFull CampoCodigo;
    private rojeru_san.RSMTextFull CampoNumero;
    private javax.swing.JComboBox ComboTipo;
    private javax.swing.JLabel americanexpress;
    private javax.swing.JLabel codigos;
    private javax.swing.JLabel dinnersclub;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSPanelShadow marco;
    private javax.swing.JLabel mastercard;
    private javax.swing.JLabel numeros;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel tarjeta_gif;
    private javax.swing.JLabel tipos;
    private javax.swing.JLabel visa;
    // End of variables declaration//GEN-END:variables
}
