/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.*;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class Ubicacion extends javax.swing.JDialog {

    /**
     * Creates new form Ubicacion
     */
    public Ubicacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        panel = new javax.swing.JPanel();
        panel2 = new rojeru_san.RSPanelShadow();
        mapa = new javax.swing.JLabel();
        BotonCerrar1 = new rojeru_san.RSButton();
        BotonVer = new rojeru_san.RSButtonRiple();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(988, 629));
        setSize(new java.awt.Dimension(988, 629));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Captura.PNG"))); // NOI18N
        panel2.add(mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 770, 380));

        BotonCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar1.setBorder(null);
        BotonCerrar1.setText("X");
        BotonCerrar1.setBorderPainted(false);
        BotonCerrar1.setColorHover(new java.awt.Color(204, 4, 17));
        BotonCerrar1.setColorText(new java.awt.Color(0, 0, 0));
        BotonCerrar1.setFocusable(false);
        BotonCerrar1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        BotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrar1MouseClicked(evt);
            }
        });
        BotonCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrar1ActionPerformed(evt);
            }
        });
        panel2.add(BotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 70, 60));

        BotonVer.setBackground(new java.awt.Color(204, 4, 17));
        BotonVer.setBorder(null);
        BotonVer.setText("Ver en Google Maps");
        BotonVer.setColorHover(new java.awt.Color(181, 18, 27));
        BotonVer.setFont(new java.awt.Font("Roboto Bold", 3, 48)); // NOI18N
        BotonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVerMouseClicked(evt);
            }
        });
        panel2.add(BotonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 630, 60));

        panel.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 810, 490));
        panel2.getAccessibleContext().setAccessibleParent(panel);

        rSPanelShadow1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 850, 510));

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 600));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.google.com/maps/place/Cinemark/@-25.568924,-54.5583532,15z/data=!4m5!3m4!1s0x0:0xb838460f581b7b7d!8m2!3d-25.568924!4d-54.5583532"));
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BotonVerMouseClicked

    private void BotonCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCerrar1ActionPerformed

    private void BotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrar1MouseClicked
        this.dispose();
    }//GEN-LAST:event_BotonCerrar1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton BotonCerrar1;
    private rojeru_san.RSButtonRiple BotonVer;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel mapa;
    private javax.swing.JPanel panel;
    private rojeru_san.RSPanelShadow panel2;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables
}
